### ISSUE TITLE
Oculus Touch - Buttons Sometimes Nonresponsive After Typing in Chat

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [jrbudda/Vivecraft_112#1]
I am using Rift+Touch on a vanilla Minecraft server with the server plugin installed. 

Issue #1: Randomly after typing in chat with the virtual keyboard, the buttons on my controllers stop working. They are still tracking, and I can still affect the world by swinging them, but pressing any button does nothing.

**Comment by AwesomeAnimationGamer** [comment]
The issue can be solved by restarting the game.

**Comment by Techjar** [comment]
Absolutely no idea. We'll need a consistent way to reproduce this issue.

**Comment by AwesomeAnimationGamer** [comment]
Huh. Must be an issue with my computer then. Oh well, getting a new one in a few weeks, hopefully that fixes it. Thanks for the quick response and keep up the epic work!

**Comment by jrbudda** [comment]
Still experiencing this?

**Comment by Techjar** [comment]
I'm gonna consider this fixed since there's been no reply.
