### ISSUE TITLE
HTC Vive - 1.12.1 Installer Issue

### ISSUE THREAD

**Issue by kojicon** [jrbudda/Vivecraft_112#10]
Whenever I try to use the installer, it said to make sure that the minecraft launcher is closed, even after restarting my pc. I also tried reinstalling the installer. Any suggestions?

**Comment by jrbudda** [comment]
yes, you should always make sure the launcher is closed, that's why it always says it.

**Comment by kojicon** [comment]
Sorry, I forgot to mention it. The launcher is closed.

**Comment by Techjar** [comment]
Yes, it always display that message whether or not the launcher is running. It's just there to let you know that you should make sure it's closed.
