### ISSUE TITLE
Vivecraft Pixelmon cannot remap controls

### ISSUE THREAD

**Issue by thatonezora** [jrbudda/Vivecraft_112#106]
I am using Vivecraft 1.12.2 and am able to bind all the normal controls without issue, but when I try to bind keys from the Pixelmon mod it acts as though nothing is binded. Specifically I was trying to bind Send Pokemon and tried the Left Touchpad, Left Trigger, Right Appmenu and I tried to map the command to the Radial manu, which didn't work. I also tried to manually bind the keys inside of the optionsviveprofiles.txt but that did not work either. I tried to look this issue up but couldn't find a way to solve it. If there are any steps I can take to fix this it would be greatly appreciated.

**Comment by PyreValors** [comment]
I am able to remap my controls, however it crashes whenever I click an attack. I originally couldn't remap either, however after a month break due to giving up and coming back it seems to work. I wish I could tell you what I'm doing different.

**Comment by PyreValors** [comment]
I now have found out by further testing battling is possible- Its just if you move your arm too fast and presumably punch/attack the hotbar for battle it crashes

**Comment by jrbudda** [comment]
Desktop window focus is important for mod compatibility, that may be the different. For crashes I will need to see a log.

**Comment by PyreValors** [comment]
Alrighty, Ill go get into a battle and purposefully punch the battle box. Where will I be able access the log?

**Comment by jrbudda** [comment]
.minecraft/logs, the vivecraft faq goes over how to find and read logs and crash reports.

**Comment by PyreValors** [comment]
This is the first time Ive ever really bothered doing anything like this so I apologize for my illiteracy and overall lack of knowledge. While going into the world and trying to purposefully crash I ran into the same issue of having my controls not work. Luckily a random pokemon decided to attack me for the fun of it.
[latest.log](https://github.com/jrbudda/Vivecraft_112/files/3234424/latest.log)

**Comment by PyreValors** [comment]
I restarted minecraft completely and the whole remapping issue resolved itself? Not too sure what caused it to begin with, but the mod does seem to work fine for the most part once figuring out what you cannot do.

**Comment by jrbudda** [comment]
So your game isnt actually crashing, it's dumping you back to the menu?

**Comment by jrbudda** [comment]
Yea it looks like its crashing the server.. you can turn off 'roomscale swinging' in the options to prevent this until I can get a fix in place.

**Comment by PyreValors** [comment]
Alright, I appreciate it, especially the quick response! ^^

**Comment by PyreValors** [comment]
I just turned off roomscale swinging, yet when I attempted the same action it still boots me? Either way Ive gone like 3 hours without crashing it except on purpose, so not an immediate issue

**Comment by jrbudda** [comment]
yea on further inspection its actually crashing on the right-click and not related to roomscale swinging.

**Comment by jrbudda** [comment]
try this one

[vivecraft-1.12.2-jrbudda-8-b2-installer.exe.zip](https://github.com/jrbudda/Vivecraft_112/files/3234978/vivecraft-1.12.2-jrbudda-8-b2-installer.exe.zip)

**Comment by PyreValors** [comment]
That works perfect! I was able to move my arms faster than a snails pace finally! I truly appreciate it.
