### ISSUE TITLE
reduced FoV is too invasive

### ISSUE THREAD

**Issue by Wapit1** [jrbudda/Vivecraft_112#110]
reduced FoV while moving is a necessity for long play time for me but the FoV is way to small when moving, if there could be an option to make it bigger while still having it

**Comment by Palimon** [comment]
Yes, absolutely!  I typically have these options on in games that provide them, but only obscuring about 10% of my view.  That helps just enough that I can play without discomfort.  This FoV reduction leaves about 30% FoV visible, which is far too much!  Please make it configurable...even if it's just in a config file.

**Comment by jrbudda** [comment]
I will add a configuration for this. In the meantime if you want to fix it on your end...
 - Find the Vivecraft library jar.  (Something like .minecraft\libraries\com\mtbs3d\minecrift\1.12.2-jrbudda-8-a4\minecrift-1.12.2-jrbudda-8-a4.jar and open in 7zip or similar.
 - Extract assets\vivecraft\shaders\fovreduction.fsh from the jar
 - Edit fovreduction.fsh in notepad
 - Find the *//arfy-barfy* section towards the bottom. Add a line a code like 
*if (circle_radius < 0.5) circle_radius = 0.5;*
to this section which will clamp the FOV at 50%. It currently goes down to 22%.
 - Put the modified fovreduction.fsh file back in the jar.

Here's a picture of what the modified code might look like.
![image](https://user-images.githubusercontent.com/1927235/59661361-ad3bef00-9178-11e9-912e-5387c70be4c5.png)

**Comment by jrbudda** [comment]
I've added this option to 1.14.3. It will likely get backported here to 1.12 at some point
