### ISSUE TITLE
Controls lack configurability

### ISSUE THREAD

**Issue by Palimon** [jrbudda/Vivecraft_112#111]
I'm trying to play Vivecraft on my MWR device (Odyssey+) and I'm having nothing but trouble with the control maps.  If I had the option to remap appropriately, I'd be loving Vivecraft.  As it stands though, it's barely playable.

__ Problem: Baked in Mappings / Hidden Mappings __
Having the baked-in mappings for each control scheme severely limits playability of Vivecraft.  Some control mappings are set in stone while others are not even available.  Due to the restrictions imposed, I cannot even use an external remapper program to fix this.

Example 1: When I select Free Movement, the trigger buttons on the left hand become forward/backward.  These mappings are not seen in the control mappings though, and cannot be changed.  In addition if I map a button to left trigger, it both moves forward and whatever action I've mapped.

Example 2: When I am using Free Movement, neither thumbstick is used for anything by the default/baked mapping. I can map actions to the right stick, but the left stick does not show up in the available controls.  That's 5 buttons on my limited interface I can't even use.

Example 3: Changing quick-slot items is done in all control schemes by swiping L/R on the trackpad.  I can't keep the tools I want in my hands because I have to press on the trackpad to use them, but miniscule L/R movement while I'm trying to press a button switches to another tool.

__ Solution __
1) Above all, show all available buttons (or axis, or whatever) and allow every mapping to be changed.  It doesn't matter whether I'm teleporting or strafing, I should be able to map jump or move forward or teleport to left on the left thumbstick, left trigger, or right click on the trackpad.
2) To maintain the ability to change between high-level VR control schemes (teleport, strafe, etc), perhaps hold mappings for each control scheme in it's own control mapping screen.  That would also make it easy to change between functional teleport and strafe control schemes as needed.

**Comment by jrbudda** [comment]
I'm pretty sure your example 1 and 3 are incorrect. 'Walk Forwards' can be rebound, as can 'Hotbar Nex/Prev'. I'm not sure about the left stick, in freemove-joy/pad mode the left stick is fully used for analog movement, so it might be excluded from the mappings, but only in that case.

**Comment by DisKorrupt** [comment]
have you tried looking into the UI controls rather than just the standard controls? also, regarding "Solution" 1, outside of left stick, it's all mappable, click the M next to the button and you can even give multiple possible mappings

**Comment by Techjar** [comment]
Yeah, you must not be looking in the right place. The Vivecraft controls screen is found in Options > VR Settings > Controller Buttons, not the vanilla controls screen. Everything you've stated here is false.

**Comment by Palimon** [comment]
I was looking in the correct place.  I've never even touched the standard control options.  Somehow in that long list, I didn't see walk forward and hotbar next/prev, so I didn't think I could map them.  I also just accidentally clicked on one already selected, and realized I could unmap controls that way.  I thought I could only map them, lol. The above helps a LOT.

That said, I still can't map the left joystick, which is a huge deficiency when all I have for controls are two little half-controllers.  I will be creating a new issue just listing that.
