### ISSUE TITLE
Left Thumbstick cannot be used during Free Movement.

### ISSUE THREAD

**Issue by Palimon** [jrbudda/Vivecraft_112#112]
When using Free Movement, nothing from the left thumbstick is available to be mapped in control mappings.

**Comment by jrbudda** [comment]
Can you confirm for me that you're in Freemove-Controller and not Freemove-Joy/Pad? I cannot see how the stick buttons would be disabled unless you're in joy/pad mode.

**Comment by Palimon** [comment]
Correct - freemove controller. Same problem in freemove hmd.

**Comment by jrbudda** [comment]
Could you upload your latest.log file here. I am baffled at this point.

**Comment by Palimon** [comment]
[latest.log](https://github.com/jrbudda/Vivecraft_112/files/3308054/latest.log)

Yes, I do have mods running. Doesn't seem like they should bother this kind of functionality, but if you need me to strip them off for cleaner logs or something, let me know.

**Comment by Techjar** [comment]
I notice you're still running v7. Use v8 (latest) and see if it still happens.

**Comment by Palimon** [comment]
I've been trying to get v8 running but can't get it to launch.  Unmodded, I instantly get a fatal error: 
[latest.log](https://github.com/jrbudda/Vivecraft_112/files/3322971/latest.log).  I'll continue to try.

**Comment by jrbudda** [comment]
if thats's the 'new, totally improved' minecraft launcher, get b10 which i uploaded just recently that has a workaround to make it work.

**Comment by Palimon** [comment]
Beat me to it - I just did :). And I can assign the left stick now!!!

**Comment by jrbudda** [comment]
ok good, i stared at that code forever and couldnt figure out your problem. Cause apparently it was already fixed.

**Comment by Palimon** [comment]
Heh sorry man!  Since I pulled the latest version about a day before I posted this, iirc, I didn't even think to check for a new version.
