### ISSUE TITLE
Version of Optifine required doesn't exist

### ISSUE THREAD

**Issue by TheDanial** [jrbudda/Vivecraft_112#115]
I'll post the crashlog at the bottom.
I've done some looking and can't seem to find the version of optifine that Vivecraft is requesting, it's almost as if it doesn't exist. can I get some help?

Failed to download file.
Name: OptiFine-1.12_HD_U_C4.jar
URL: https://libraries.minecraft.net/optifine/OptiFine/1.12_HD_U_C4/OptiFine-1.12_HD_U_C4.jar
Error details: The requested URL returned error: 404 Not Found
Filename on disk: OptiFine-1.12_HD_U_C4.jar
Path: C:\Users\[user name]\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.12_HD_U_C4\OptiFine-1.12_HD_U_C4.jar
Exists: Nonexistent

**Comment by Techjar** [comment]
The installer should download OptiFine, this error means it didn't.

**Comment by TheDanial** [comment]
The installer tried to, and couldn't for the reason I just posted. apologies for forgetting that detail.
"as if it didn't exist"

**Comment by Techjar** [comment]
No, that's the launcher failing to download it. The installer is supposed to download it from a different location.

**Comment by TheDanial** [comment]
so should I just run the installer again?

**Comment by Techjar** [comment]
Yeah, and report back if the installer itself gives any error.

**Comment by TheDanial** [comment]
well, I still don't know what the issue was, but it seemed to succeed this time. thanks for the help.

**Comment by Techjar** [comment]
Probably a spurious connection error.
