### ISSUE TITLE
Can't rebind teleport

### ISSUE THREAD

**Issue by JoeMBlair** [jrbudda/Vivecraft_112#12]
Whenever I try to open inventory or Jump it also teleports me. So I'm wondering if you could make teleport rebindable.

**Comment by jrbudda** [comment]
I'm preeettty sure the teleport button is just Move Forward in the bindings. Make sure your regular minecraft keyboard bindings aren't something weird.

**Comment by JoeMBlair** [comment]
I did at one point set it to joypad movement. Would switching back to teleport after that mess up my bindings?

**Comment by jrbudda** [comment]
not the bindings but it might make the touchpad activate teleport, since Move Forward is not used in Joy/Pad mode.

**Comment by JoeMBlair** [comment]
Yea I changed the free movement to something else and switched backed to teleport and the left trigger binding worked again. You might want to make it so teleport movement doesn't inherit joypad binding for movement.

**Comment by jrbudda** [comment]
this is fixed in the upcoming r5 release.
