### ISSUE TITLE
Crash on init

### ISSUE THREAD

**Issue by ItsK1tty** [jrbudda/Vivecraft_112#122]
Got crashed with nothing. See log file
[crash-2019-07-24_23.21.30-client.txt](https://github.com/jrbudda/Vivecraft_112/files/3428649/crash-2019-07-24_23.21.30-client.txt)

**Comment by jrbudda** [comment]
Did you change the 'Game Directory' during installation?

**Comment by ItsK1tty** [comment]
I did

**Comment by ItsK1tty** [comment]
Fixed by changing directory to c:\1\1 instead of c:\1
closed
