### ISSUE TITLE
[Mod incompatibility][Forge Mod][Request] Advent of Ascension and Vivecraft Compatibility 

### ISSUE THREAD

**Issue by Herbertofury** [jrbudda/Vivecraft_112#123]
I am mainly just curious if it is a possibility. Making these two compatible would be amazing. The gun appears correctly and looks super cool in VR, but I just can't shoot even with Bow interaction turned off. V9 of vivecraft causes constant crashes for me despite what I do even with Vanilla minecraft. V8 works fine which is why I am using V8.

Minecraft Version: 1.12.2
A0A3 Version: 3.1.2.b
Vivecraft Version: V8

**Comment by Techjar** [comment]
I'm more interested in the crashes. You gotta report that shit man, not just use an old version. :/

**Comment by Herbertofury** [comment]
> I'm more interested in the crashes. You gotta report that shit man, not just use an old version. :/

I will work on sending crash logs and ect with V9 to help out. Just been testing everything I can. A0A3 gun fix I just thought might be a possibility unlike portal mod due to coding. It would be like a super fun VR arcade shoot em up if you ever tried this mod.

**Comment by jrbudda** [comment]
these guns appear to use the vanilla onItemRightClick so I have no idea why they wouldn't work.

**Comment by Herbertofury** [comment]
> these guns appear to use the vanilla onItemRightClick so I have no idea why they wouldn't work.
You right, they are working perfectly. THIS IS AWSOME!!!, you guys should really try it out if you have not already. Feel free to change to V9 Crashing, I am going to upload logs and what not now and my attempts.
