### ISSUE TITLE
[V9][Crash][Multi-MC] 

### ISSUE THREAD

**Issue by Herbertofury** [jrbudda/Vivecraft_112#124]
Vivecraft Version: V9
Forge Version: 14.23.5.2838
No Mods vanilla minecraft 1.12.2

![Pictsdfsdfure1](https://user-images.githubusercontent.com/18050735/62416539-eed60b80-b5f9-11e9-95d4-505fb8fb5904.png)
![Pictufsdfre1](https://user-images.githubusercontent.com/18050735/62416541-f3022900-b5f9-11e9-9ceb-c9b84d965c8b.png)

**Comment by jrbudda** [comment]
you're missing the jvm args, perhaps you did not close multimc while installing.

**Comment by Herbertofury** [comment]
reinstalled everything again, I had Multimc closed when installing Vr first time. But now it is working no problems. No clue why It was giving me issues the first few times.

**Comment by Herbertofury** [comment]
Thanks for the quick support, everything is working perfectly. Loving the new fun arcade shooter now with a0a3 and mowzie mobs.
