### ISSUE TITLE
Installing requires Java 1.6

### ISSUE THREAD

**Issue by Mattz0r** [jrbudda/Vivecraft_112#13]
Hello,

I have recently purchased a Vive, and looking forward to trying Minecraft in VR. However, I don't want to install an obsolete version of Java in order to do so.

Please can you find a way for me to install this without having Java version 6 installed.

Thanks,

Matt

**Comment by TheTrueForce** [comment]
To clarify, have you downloaded the installer and run into a wall with it, or did you find that elsewhere?
Because I think the installer works with a fairly recent Java(I think it was 8).

**Comment by wolrah** [comment]
I can definitely not replicate this problem.  I just installed from vivecraft-1.12.1-jrbudda-3r4-installer.exe on a system running Java 1.8.0_144 and everything worked as expected.

**Comment by TheTrueForce** [comment]
Yeah, everything works with Java 8. Minecraft, the Vivecraft installer, and Vivecraft itself.
It occurs to me that it might have been saying you need at least Java 6. So Java 8 will work. You might need to install Java. Minecraft keeps its own little install, but that doesn't work for the rest of the system.
