### ISSUE TITLE
Simple Side by Side display mode?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [jrbudda/Vivecraft_112#134]
I don't want a headset or a Gyro something to move visuals with my head,  
I use keyboard and mouse and just want a Side by Side 3D mode  
just like the built in anaglyph 3d's side by side version.

The thing is, I have a 4K phone and now there is a Moonlight opensource software  
can utilize Nvidia Shiled to stream game from PC to Android and have relative low lantency.
And I have Google Cardboard, that means if Minecraft Java Edition enabled side by side 3d,  my phone can use it and bring 1080p 3d visual.

Now Vivecraft installed and report "Render Setup Failed, VR Headset not detected"  
But I don't... Just use keyboard and mouse will able to do play...

**Comment by TheTrueForce** [comment]
Vivecraft can come close to achieving the effect you want using Seated Mode. You can turn using the mouse, but not look up and down, as that'd be near-instant motion sickness. That's why the gyro is used.

However, you must have something that presents a headset to SteamVR for Vivecraft to work. I'm told Trinus can do that with a phone.
Vivecraft only ever deals with VR hardware via SteamVR. That way, they don't have to re-implement everything every time a new headset comes out.

**Comment by mhtvsSFrpHdE** [comment]
@TheTrueForce 

I download SteamVR and Trinus...with Google Cardboard settings.  
And follow the install guid...  
Well...Very unfortunately, it's not playable.

With Trinus, low resolution, low fps, phone is very hot... wrong display direction...
No a place to adjust sensor, no control method thus can't even join the game...

Maybe I'm doing wrong. There are many YouTube video still shows fun game play with vivecraft.

What I expect is just a simple 3D display experience but not VR.  
With Moonlight streaming and some Side by Side 3D support software, I can already get a fine experience but VR and Minecraft isn't.  
I can understand vivecraft is focus on VR so the 3D display wishers like me are finding wrong mod project.

You have my thanks. I check the news and find even Mojang is going to remove the "Anaglyph 3D" from Minecraft 1.13.  
So sad. I forged my cheap 3D monitor but found no 3D contents available.  
Anyway, fairly well my friend and good bye.

**Comment by Techjar** [comment]
Maybe you'll have better luck with Riftcat Vridge.

**Comment by mhtvsSFrpHdE** [comment]
@Techjar I then later check that but feels hopeless.  
All I have is a Snapdragon 835 Android phone running Android 9.0 Pie,  
A Geforce 1050Ti graphic card, keyboard, mouse, and Google Cardboard.  
No HTC, No Steam, No PSVR... Not owned any virtual reality solution.

Do you think I can play Minecraft via vivecraft like before,  
sit there using keyboard and mouse with just addition 3D visual?  
Keyboard is fine but mouse may not,  
I find that vivecraft render scope will not scale up with Java window Maximize or change resolution.  
I maximize Java window but vivecraft still display small at left bottom corner.
