### ISSUE TITLE
Certain shaderpacks cause left eye to be rendered brighter than right eye

### ISSUE THREAD

**Issue by christofin** [jrbudda/Vivecraft_112#139]
As discussed in Discord. I'm opening a ticket here for tracking so I can also easily update it as I test more shaders. 

Certain shaderpacks are causing the left eye to be rendered at a significantly higher brightness level than the right eye. This is extremely noticeable, and only present in the Nether with certain shaders. So far, I've been able to replicate this issue 100% of the time with Sildur's Vibrant Shaders (all versions, even the lite version). 

Things tested:
- All quality settings in the Optifine video menus
- Specific shader settings: TAA (which should be 'off' in VR), bloom, lens flares, color values, and more
- With or without resource packs
- When logging in in the Nether, as opposed to logging in in another dimension then moving into the Nether

VR headset: Valve Index. I wasn't able to test other headsets, but other users in Discord reported not having the issue with Oculus hardware. 

![20200203_162909](https://user-images.githubusercontent.com/43354771/73978477-6a42ad80-48fa-11ea-95a1-4984602bffdc.jpg)

![20200203_162902](https://user-images.githubusercontent.com/43354771/73978480-6b73da80-48fa-11ea-8ab1-31004dcbadf4.jpg)

When trying to see how it looks on my monitor, the left eye isn't rendered at all, very interesting. 

Also, when I pull up the pause menu, the left eye does render normally, but as soon as I exit the pause menu, the brightness/gamma immediately shoots back up. 

More info: 

- I'm on the latest version of Vivecraft available for 1.14.4
- Latest version of SteamVR, non beta branch
- Tested in both fullscreen and windowed mode (for the Minecraft Client itself) - issue is present in both

**Comment by jrbudda** [comment]
Technically this is the issue tracker for Vivecraft 1.12, not 1.14, do you have any idea if the issue is present in the 1.12.2 version?

**Comment by christofin** [comment]
I haven't tested, but let me actually move this to the 1.14.4 Github, sorry about that. I'll test for the issue in previous versions tonight.
