### ISSUE TITLE
NonVR Players Crashing Near End Portal

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [jrbudda/Vivecraft_112#14]
I host a public Survival server, and some of my players play using the NonVR Companion Mod. Just last night, something went wrong, and now players running it can no longer get close to the End Portal without their entire game crashing. If they log back in, they crash again within a second. Running /kill as soon as they log in allows them to respawn after another crash, and then everything is fine. The server console logs no error code, and the End Portal has been accessible for quite some time with no issues. I would also like to note that this does not happen for all players running NonVR, but most. Players actually using a VR headset are not affected, as well as vanilla players. I have attached a crash report from one of the affected players.
[crash-2017-09-14_19.45.49-client.txt](https://github.com/jrbudda/Vivecraft_112/files/1306391/crash-2017-09-14_19.45.49-client.txt)

**Comment by jrbudda** [comment]
Do you know if this only happens with Forge or not?

**Comment by AwesomeAnimationGamer** [comment]
Not sure. I looked up the error it gives, and the only thing I found was that it could happen when Smooth FPS is enabled in Optifine. Toggling the setting did not fix it for them.

**Comment by jrbudda** [comment]
I couldn't reproduce it using just Forge with no mods. Just to be totally sure I incremented the version and rebuilt the NONVR companion for 1.12 and uploaded it to github, could you have them try that first just to make sure there isn't an outdated version problem? (4r3)

**Comment by AwesomeAnimationGamer** [comment]
I'll have them try it. I'll let you know what happens. Is it the same download they would have used before, or is it a different link?

**Comment by jrbudda** [comment]
Same github releases page, i just updated the file

**Comment by AwesomeAnimationGamer** [comment]
Sorry for the confusion, this issue is happening on 1.12, not 1.12.1. I can't update the server yet as I'm waiting on a few plugins to update.

**Comment by jrbudda** [comment]
Oh sorry i missed that bit... uhh that's a problem as I do not have the nonvr code under version control and 1.12.1 totally replaced 1.12.0, I don't have an easy way to go back and rebuild 1.12.0 non-vr. You may have to wait til you can update to .1. What mods are you still waiting on?

**Comment by AwesomeAnimationGamer** [comment]
Actually I think I just figured it out. The install was failing, and I managed to get it to install by itself and then copy it over. I'll have them test on 1.12.1

**Comment by AwesomeAnimationGamer** [comment]
Good news: That worked! Upgrading to 1.12.1 fixed the issue! Thanks for your help!
