### ISSUE TITLE
Installing Vivecraft into a Twitch Modpack?

### ISSUE THREAD

**Issue by Fleepy** [jrbudda/Vivecraft_112#140]
I've been trying to play Project Ozone 3 with Vivecraft but I don't know how to properly install it.
I set the minecraft install location to there the install is (Usually Twitch/Install)
and I selected custom modpack and put in my modpack (For me it was D:\Games\Twitch\Instances\Project Ozone 3 A New Way Forward (2))

But when I open the modpack in twitch, i dont see vivecraft. only the regular forge profile.

**Comment by Techjar** [comment]
http://www.vivecraft.org/faq/#modpacks

**Comment by Fleepy** [comment]
thanks.

**Comment by Fleepy** [comment]
Nevermind. I tryed running it and it says it cant download forge
![image](https://user-images.githubusercontent.com/18307183/74615628-70454500-50d7-11ea-921c-cc54a9032ffa.png)

**Comment by Techjar** [comment]
That's not supposed to be downloaded by the launcher, the installer should have put it in. Somehow forge isn't installed properly.

**Comment by Fleepy** [comment]
Ok i manually downloaded it myself from the same website it with a different url, now it cant find this library
![image](https://user-images.githubusercontent.com/18307183/74615733-1db85880-50d8-11ea-9bc3-4c2f1aadddf9.png)

**Comment by Techjar** [comment]
Don't do that. Install Forge, it's not installed properly.

**Comment by Techjar** [comment]
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-installer-win.exe

**Comment by Fleepy** [comment]
Awesome i got it work. Thanks

**Comment by Techjar** [comment]
The Vivecraft installer is supposed to run the Forge installer automatically so I'm not sure how it was messed up.
