### ISSUE TITLE
I tried to open the non-vr installer, but my computer said it was corrupted data! Please fix this problem as quick as possible!

### ISSUE THREAD

**Issue by Linkplays** [jrbudda/Vivecraft_112#149]
I tried to open the non-vr installer, but my computer said it was corrupted data! Please fix this problem as quick as possible!

**Comment by Linkplays** [comment]
Here is an image of what it says.
<img width="1440" alt="Screen Shot 2020-05-22 at 4 57 20 PM" src="https://user-images.githubusercontent.com/62623343/82708898-663e5f80-9c4d-11ea-8774-b08b02742c98.png">

**Comment by Techjar** [comment]
Rename it to .jar
