### ISSUE TITLE
intel integrated graphic's are not  supported

### ISSUE THREAD

**Issue by Bluewolf2** [jrbudda/Vivecraft_112#155]
So a message pop's up on my screen when ever I try to open vivecraft saying Render setup failed: Intel integrated graphics are not supported if this is a labtop, please force the high-performance GPU. Detected GPU: intel(r) UHD graphics, can I fix this

**Comment by Techjar** [comment]
http://www.vivecraft.org/faq/#gpu

**Comment by Bluewolf2** [comment]
could this possibly be fixed in the future

**Comment by Techjar** [comment]
Could what be fixed?

**Comment by Bluewolf2** [comment]
my graphics card is not compatible with vivecraft so could it be in the future

**Comment by Techjar** [comment]
Did you read the FAQ section I linked?

**Comment by Bluewolf2** [comment]
oh sorry i didn't see that

**Comment by Bluewolf2** [comment]
ok so how do I  create a High performance setting for the java runtime that launches Minecraft.

**Comment by Techjar** [comment]
On a laptop with AMD graphics? That should be covered there as well.

**Comment by Bluewolf2** [comment]
ok

**Comment by Bluewolf2** [comment]
I'm having a bit of trouble with its directions could you hep me

**Comment by Techjar** [comment]
I don't know how to make it any more clear.

**Comment by Bluewolf2** [comment]
sorry just got it im checking right now

**Comment by Bluewolf2** [comment]
thank you for your help its working now
