### ISSUE TITLE
Minecraft Forge Crash 1.15.2

### ISSUE THREAD

**Issue by TerraShiii** [jrbudda/Vivecraft_112#159]
"The game crashed whilst initializing game
Error: java.lang.VerifyError: Bad local variable type
Exit Code: -1" 
I got that error and I don't know what's going on. This only started after putting a specific mod onto my minecraft, upon removal of the mod from my mods folder, the error persisted. How can I solve this?

**Comment by Espergium** [comment]
Forge is broken for vivecraft 1.15.2. Don't use forge for this release of vivecraft.
