### ISSUE TITLE
Mod creative tabs are unavailable

### ISSUE THREAD

**Issue by 5t00** [jrbudda/Vivecraft_112#16]
Whenever I load up any Forge mods to play with Vivecraft 1.12.1, the creative mode inventory tabs aren't reachable. The tabs themselves seem to render beneath the vanilla tabs on page 1, and no other pages are available (as in vanilla).

To illustrate: 
I attempted to add MineColonies for 1.12.1 with no other mods. When I do this in non-Vivecraft Minecraft, the first creative inventory screen looks like this:
![non vr inventory 1](https://user-images.githubusercontent.com/28825922/30710473-4753db0e-9ecb-11e7-9435-65d72d2d9c11.png)

And then the second page has a single tab for MineColonies:
![non vr inventory 2](https://user-images.githubusercontent.com/28825922/30710476-4949b186-9ecb-11e7-817c-9252b3403882.png)

When I load it in Vivecraft, there is only one page available. The MineColonies tab appears to underlay the first Minecraft tab, and the MineColonies items are unavailable:
![vr inventory](https://user-images.githubusercontent.com/28825922/30710464-432431a0-9ecb-11e7-92a6-0eb60dad34f8.png)

(Apologies for the screenshot quality!)

**Comment by jrbudda** [comment]
Thank's. I'll take a look.

**Comment by jrbudda** [comment]
[vivecraft-1.12.1-jrbudda-3final-installer.exe.zip](https://github.com/jrbudda/Vivecraft_112/files/1325672/vivecraft-1.12.1-jrbudda-3final-installer.exe.zip)

see if this fully fixes the issue

**Comment by 5t00** [comment]
That clears up the rendering issue, but the other pages of creative tabs still aren't available.

**Comment by jrbudda** [comment]
What other pages? I tried it with Minecolonies and it looks right to me 
https://gyazo.com/ad0df071ce289a8820e33b84892dc9c9

**Comment by 5t00** [comment]
You're right, it works - I just didn't get Forge integration installed along with your final version before. Mod tabs are available now, and it also looks like JEI works again!

Thanks for making this, and for your quick responses!
