### ISSUE TITLE
Optifine 1.15.3 not working with Mod list

### ISSUE THREAD

**Issue by RaffHzTM** [jrbudda/Vivecraft_112#161]
Hey there,

Whenever I try to load Optifine with my mod list I receive this error:

The game crashed whilst initializing game
Error: java.lang.VerifyError: Bad local variable type
Exit Code: -1****

Any chance anyone knows how to fix this? I've tried using OptiForge and different versions of Optifine previously but nothing seems to fix it.

The mods I'm currently using are as linked below:
[mods (1).zip](https://github.com/jrbudda/Vivecraft_112/files/5489651/mods.1.zip)

**Comment by TropheusJ** [comment]
>issue is under vivecraft 1.12
>optifine 1.15.3
>adding your own optifine
there is so much wrong here. what versions of everything are you even using?

**Comment by RaffHzTM** [comment]
> > issue is under vivecraft 1.12
> > optifine 1.15.3
> > adding your own optifine
> 
> there is so much wrong here. what versions of everything are you even using?

I'm trying to use OptiFine 1.16.3 HD U G4 with the latest version of Forge and OptiForge 1.6.3-0.3.4.
All the mods are using 1.16.3.

Sorry if I'm a pain, I'm brand new to all of this :)

**Comment by TropheusJ** [comment]
1. vivecraft already has optifine in it
2. both optifine and vivecraft are incompatible with latest forge, optiforge does not help in this situation

**Comment by TropheusJ** [comment]
3. this is the 1.12 repo

**Comment by RaffHzTM** [comment]
> 1. this is the 1.12 repo

What does all of this mean? lmao

**Comment by TropheusJ** [comment]
it means do not use forge on 1.16.3 currently. wait for 1.16.4 and everything to update. most mods should just work from 1.16.3, and even .2.

**Comment by TropheusJ** [comment]
and do not add optifine.

**Comment by RaffHzTM** [comment]
So use Forge 1.16.4 and don't add Optifine into the mod folder?

**Comment by TropheusJ** [comment]
1. do not add optifine, vivecraft has it built in.
2. do not use forge versions other than the default.

**Comment by RaffHzTM** [comment]
I don't have Vivecraft in the mod list though

**Comment by TropheusJ** [comment]
do you realize where this issue is opened?

**Comment by RaffHzTM** [comment]
OH SHIT, I AM SO SORRY

**Comment by RaffHzTM** [comment]
I've never made a post on here before

**Comment by RaffHzTM** [comment]
I am so sorry holy shit

**Comment by TropheusJ** [comment]
ha, don't worry about it.

**Comment by RaffHzTM** [comment]
Should I just repost in the right thread then?

**Comment by TropheusJ** [comment]
where exactly is the right thread? are you even using vivecraft?

**Comment by RaffHzTM** [comment]
No, I didn't even realise I was posting on Vivecraft, I'm just trying to get these mods working with Optifine

**Comment by TropheusJ** [comment]
for just optifine, go to https://github.com/sp614x/optifine/issues/

**Comment by RaffHzTM** [comment]
Tysm, I'm so sorry for the hassle lmao
