### ISSUE TITLE
Why intel not supported

### ISSUE THREAD

**Issue by Cheez409** [jrbudda/Vivecraft_112#176]
I wanted to play VR Minecraft Then I saw that intel is not supported

**Comment by Techjar** [comment]
Because it's not powerful enough for VR and the driver sucks.

**Comment by Cheez409** [comment]
What Graphics cards you support?

**Comment by Techjar** [comment]
Anything nvidia or amd that can actually run VR. To be clear it's not that we don't support Intel, it's more like it doesn't support us because the driver screws something up.

**Comment by Cheez409** [comment]
Thanks!
