### ISSUE TITLE
ViveCraft works with Fancy Block Particles on MC1.12.1 but not on MC1.12.2

### ISSUE THREAD

**Issue by TominoCZ** [jrbudda/Vivecraft_112#18]
I have no idea how this happened, but it seems that our mods collided somewhere around the ParticleManager. My mod sets the minecraft's particleManger to my own just as the world loads.
Which might be why I see the whole world all grey and with no perspective to it(right when the world loads)... like.. not grey textures but.. just.. grey.. (try it yourself with the latest version)

The thing I don't understand is how a particle manager can cause something like this.

**Comment by jrbudda** [comment]
Nothing surprises me anymore. I will take a look. Are you getting a specific log error?

**Comment by jrbudda** [comment]
I am 100% sure the problem is you're replacing the entire EntityRenderer instance after the game has initialized and a world has loaded. 

I am not at all sure how that every worked before, it's not something to do lightly. Did you recently add the FPEntityRenderer or something?

**Comment by jrbudda** [comment]
We did isolate the difference between vivecraft and vanilla that allows you to late-swap the EntityRenderer while in-game without blowing up. That will be added to Vivecraft in next build. I'd highly recommend, tho, making your changes to EntityRenderer via ASM instead of replacing the instance. At eh very least I think you're also missing a call to mcResourceManager.registerReloadListener after changing the instance.

**Comment by Techjar** [comment]
I'd like to add, for the asm route, you can use Sponge Mixin to make it very easy to replace the method with your own. No messing around in raw asm/bytecode required.

**Comment by TominoCZ** [comment]
I really want to avoid ASM though..

**Comment by Techjar** [comment]
Well what you're doing right now is worse than ASM, as you are automatically incompatible with any other mod that replaces EntityRenderer. ASM is generally the most compatible way to modify base code, though should be avoided if there's a cleaner way to do it. Completely replacing a base class instance, however, is not a clean way.
