### ISSUE TITLE
I  got  an  ERROR

### ISSUE THREAD

**Issue by RNCrat** [jrbudda/Vivecraft_112#181]
its says Intel graphics are not supported

**Comment by Espergium** [comment]
Intel integrated is not supported. You need a dedicated GPU.
http://www.vivecraft.org/faq/#gpu

**Comment by RNCrat** [comment]
But is there anyway to get around that? I don't have a spare 1,000 dollars!

**Comment by Espergium** [comment]
No. Intel drivers just don't work and they don't seem inclined to care.

**Comment by RNCrat** [comment]
:(
