### ISSUE TITLE
Failure to launch game

### ISSUE THREAD

**Issue by devontheyoutuber** [jrbudda/Vivecraft_112#185]
Not sure why it isnt working I started the game but its refusing to launch and giving me the same error already done the steps it told me to do. Launching any other version works just not Vivecraft
![image](https://user-images.githubusercontent.com/50086348/130465899-d3b558d8-4d0b-4298-9baa-ce53f009e7c5.png)

https://pastebin.com/YmWSNVhg

**Comment by Techjar** [comment]
We don't support TLauncher. Also, based on the error, it looks like TLauncher itself is broken.
