### ISSUE TITLE
Vive controllers are tracking but the buttons are not working at all.

### ISSUE THREAD

**Issue by Pyroglyph** [jrbudda/Vivecraft_112#19]
Running a fresh install of Java 1.8.0_151 (32-bit) on Windows 10 Fall Creators Update (64-bit).

The game launches to the main menu and I can point around with my controller (I can see my controller model as well as the in-game model for some reason, only tested once) but I can't press any buttons. Instead I have to use my mouse to click things.

When I get into the world I can't do anything except look around and destroy blocks by swinging my arm (not clicking). It's like it's not registering button input from the controllers at all. I can also see my controllers through my arms (but I haven't thoroughly tested that).

Something else I noticed is that if I hold W on the keyboard, the arc teleporter appears and I can move around with that.

I'll investigate further (including trying the 64-bit version of Java) and I'll add anything else related I find.

**Comment by Techjar** [comment]
Sounds like something in the SteamVR overlay is open (such as the keyboard), which displays the controller models and prevents inputs from being passed to the game.

**Comment by jrbudda** [comment]
Yea def a SteamVR problem. Theres been some odd reports of issues with the controller skins in the SteamVR Settings. I assume you're playing unmodded?

**Comment by Pyroglyph** [comment]
I already checked the overlay and it seems fine. Nothing unusual is open.

The client is untouched apart from whatever Vivecraft modified with it's installer.

I can also confirm that the game isn't receiving button input because after a restart the issue persists and trying to change the controls in the menu does nothing.

I found that the version of Java the game is using is it's own runtime (1.8.0_25). Updating this to 1.8.0_151 made no difference.

**Comment by Techjar** [comment]
Have you already tried restarting Steam (not just SteamVR)? Sometimes it gets into a weird and makes things misbehave.

**Comment by Pyroglyph** [comment]
It seems to have resolved by restarting Steam. Cheers for the help :)

I find it very odd that restarting my computer didn't help...

**Comment by Techjar** [comment]
That... doesn't make much sense, but glad you got it fixed.
