### ISSUE TITLE
Vivecraft Laptop Loading Issue (Virtual Desktop/SteamVR)

### ISSUE THREAD

**Issue by Diamond1015** [jrbudda/Vivecraft_112#191]
I have tried my ways to try and get this to work. However, I'm unable to. I've tried the FAQ way, and allocated half my ram to try and give it more performance power, but nothing seems to be working. Same error message every time: "Render Setup Failed: Intel Integrated Graphics cards are not supported. If this is a laptop, please force into high-performance GPU. Detected GPU: Intel(R) UHD Graphics"
Here's a link to my laptop. If anyone could help that'd be great:
https://www.newegg.com/p/N82E16834233489

**Comment by fayer3** [comment]
did you try the `The game shows up on my desktop, but not in the headset!`, from the faq?
http://www.vivecraft.org/faq/#gpu

**Comment by Diamond1015** [comment]
Interesting thought, ill give it a go

**Comment by Diamond1015** [comment]
I have tried the Secondary List in the section you listed, and it didn't work.

**Comment by fayer3** [comment]
you did go through the first list, to determine the correct javaw.exe? and set it for that?

**Comment by Diamond1015** [comment]
Now I feel like an idiot! Thanks for the reminder fayer3.
