### ISSUE TITLE
Cant install forge

### ISSUE THREAD

**Issue by DooDooBrain21** [jrbudda/Vivecraft_112#195]
I have tried to install vivecraft with forge however it keeps throwing an error during installation (Could not download from https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2854-installer.jar to forge-1.12.2-14.23.5.2854-installer.jar sun.security.validator.ValidatorExeption: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderExeption: unable to find valid certification path to requested target), is there any way to fix the issue.

**Comment by fayer3** [comment]
if I remember correctly, this can be fixed by updating your java version

**Comment by DooDooBrain21** [comment]
thanks that worked.
