### ISSUE TITLE
Vivecraft installer 4R3 Triggers Win10 AV

### ISSUE THREAD

**Issue by Omnicrola** [jrbudda/Vivecraft_112#20]
It's not clear what Windows defender thinks is wrong with it, but attempting to download the vivecraft-1.12.2-jrbudda-4r3-installer.exe file triggers the Windows 10 antivirus and it is immediately deleted.  I went back one version and downloaded V3 of 1.12.2 and the AV did not seem to mind.

**Comment by jrbudda** [comment]
I cannot control this at all.
