### ISSUE TITLE
game crashes when loading world

### ISSUE THREAD

**Issue by c0smicSalm0n** [jrbudda/Vivecraft_112#203]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  AALoadingPlugin (arcanearchives-0.2.0.25-mixins8.jar)
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  Backpacked (backpacked-1.4.3-1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 11/3/22 1:47 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.client.renderer.entity.RenderPlayerVR cannot be cast to net.minecraft.client.renderer.entity.RenderPlayer
	at goblinbob.mobends.standard.client.event.RenderingEventHandler.beforeHandRender(RenderingEventHandler.java:29)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1118_RenderingEventHandler_beforeHandRender_RenderHandEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:774)
	at net.optifine.reflect.ReflectorForge.renderFirstPersonHand(ReflectorForge.java:83)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:2024)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1449)
	at net.minecraft.client.Minecraft.renderSingleView(Minecraft.java:4698)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:647)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.vivecraft.main.VivecraftMain.main(VivecraftMain.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at goblinbob.mobends.standard.client.event.RenderingEventHandler.beforeHandRender(RenderingEventHandler.java:29)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1118_RenderingEventHandler_beforeHandRender_RenderHandEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:774)
	at net.optifine.reflect.ReflectorForge.renderFirstPersonHand(ReflectorForge.java:83)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:2024)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1449)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['C0smicSalm0n'/1385, l='MpServer', x=146.56, y=76.13, z=254.38]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 06 - quark_realistic, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (148,64,256), Chunk: (at 4,4,0 in 9,16; contains blocks 144,0,256 to 159,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 76 game time, 76 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 38 total; [EntityBat['Bat'/512, l='MpServer', x=64.38, y=30.22, z=243.03], EntitySkeleton['Skeleton'/513, l='MpServer', x=77.50, y=24.00, z=311.50], EntityStoneling['Stoneling'/514, l='MpServer', x=70.50, y=23.00, z=319.50], EntityPig['Pig'/648, l='MpServer', x=100.50, y=75.00, z=318.50], EntityPig['Pig'/649, l='MpServer', x=98.50, y=75.00, z=322.50], EntityPig['Pig'/650, l='MpServer', x=98.50, y=76.00, z=320.50], EntityPig['Pig'/651, l='MpServer', x=100.20, y=76.00, z=321.29], EntityPig['Pig'/671, l='MpServer', x=142.50, y=73.00, z=175.50], EntityPig['Pig'/672, l='MpServer', x=141.50, y=73.00, z=175.50], EntityPig['Pig'/673, l='MpServer', x=143.50, y=74.00, z=177.50], EntityCrab['Crab'/674, l='MpServer', x=143.50, y=72.00, z=249.50], EntityCrab['Crab'/675, l='MpServer', x=143.50, y=72.00, z=249.50], EntityPig['Pig'/705, l='MpServer', x=146.44, y=75.00, z=177.26], EntityMimic['Mimic'/706, l='MpServer', x=156.50, y=34.00, z=262.50], EntityLizard['Lizard'/838, l='MpServer', x=198.50, y=86.00, z=204.50], EntityMimic['Mimic'/839, l='MpServer', x=205.50, y=22.00, z=247.50], EntityNautilus['Nautilus'/587, l='MpServer', x=94.76, y=59.27, z=204.09], EntityPig['Pig'/843, l='MpServer', x=222.52, y=77.00, z=291.05], EntityBlueSlime['Blue Slime'/588, l='MpServer', x=89.80, y=169.00, z=223.86], EntityPig['Pig'/844, l='MpServer', x=219.50, y=78.00, z=291.50], EntityBlueSlime['Blue Slime'/589, l='MpServer', x=87.79, y=169.00, z=222.65], EntityPig['Pig'/845, l='MpServer', x=219.50, y=78.00, z=293.50], EntityBlueSlime['Blue Slime'/590, l='MpServer', x=88.14, y=169.00, z=219.78], EntityPig['Pig'/846, l='MpServer', x=217.74, y=79.00, z=294.43], EntityBlueSlime['Blue Slime'/591, l='MpServer', x=85.31, y=169.42, z=217.70], EntityZombie['Zombie'/592, l='MpServer', x=89.50, y=47.00, z=256.50], EntityBat['Bat'/1391, l='MpServer', x=68.43, y=28.74, z=213.80], EntityMimic['Mimic'/752, l='MpServer', x=175.50, y=39.00, z=214.50], EntityBat['Bat'/1392, l='MpServer', x=82.25, y=32.29, z=308.90], EntityStoneling['Stoneling'/505, l='MpServer', x=75.34, y=16.00, z=204.37], EntityFallingBlock['Falling Block'/1017, l='MpServer', x=257.50, y=32.00, z=265.50], EntitySkeleton['Skeleton'/1401, l='MpServer', x=94.50, y=48.00, z=261.50], EntityWitch['Witch'/506, l='MpServer', x=77.50, y=16.00, z=208.50], EntityBat['Bat'/507, l='MpServer', x=70.15, y=13.55, z=236.66], EntityBat['Bat'/509, l='MpServer', x=69.43, y=30.80, z=249.73], EntityBat['Bat'/510, l='MpServer', x=64.53, y=30.77, z=245.53], EntityPlayerSP['C0smicSalm0n'/1385, l='MpServer', x=146.56, y=76.13, z=254.38], EntityBat['Bat'/511, l='MpServer', x=66.95, y=30.96, z=248.42]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:3667)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:676)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.vivecraft.main.VivecraftMain.main(VivecraftMain.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2394432360 bytes (2283 MB) / 4205838336 bytes (4011 MB) up to 4205838336 bytes (4011 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms4G -XX:+UseParallelGC -XX:ParallelGCThreads=3 -XX:MaxGCPauseMillis=3 -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 67 mods loaded, 67 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version                  | Source                                        | Signature                                |
	|:------ |:--------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                   | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                         | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                         | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                       | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | backpacked                  | 1.4.2                    | backpacked-1.4.3-1.12.2.jar                   | None                                     |
	| LCHIJA | obfuscate                   | 0.4.2                    | minecraft.jar                                 | None                                     |
	| LCHIJA | mercurius_updater           | 1.0                      | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| LCHIJA | antiqueatlas                | 4.6.3                    | antiqueatlas-1.12.2-4.6.3.jar                 | None                                     |
	| LCHIJA | antiqueatlasoverlay         | 1.2                      | antiqueatlas-1.12.2-4.6.3.jar                 | None                                     |
	| LCHIJA | arcademod                   | 2.1.5                    | arcademod-2.1.5-1.12.2.jar                    | None                                     |
	| LCHIJA | baubles                     | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | gbook_snapshot              | 2.9.1.s5                 | Guidebook-1.12.2-2.9.1.s5.jar                 | None                                     |
	| LCHIJA | arcanearchives              | 0.2.0.25-mixins8         | arcanearchives-0.2.0.25-mixins8.jar           | None                                     |
	| LCHIJA | architecturecraft           | @VERSION@                | architecturecraft-1.12-3.98.jar               | None                                     |
	| LCHIJA | artifacts                   | 1.12.2-1.2.3             | Artifacts-1.12.2-1.2.3.jar                    | None                                     |
	| LCHIJA | jei                         | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCHIJA | tombstone                   | 4.5.12                   | tombstone-4.5.12-1.12.2.jar                   | None                                     |
	| LCHIJA | quark                       | r1.6-179                 | Quark-r1.6-179.jar                            | None                                     |
	| LCHIJA | autoreglib                  | 1.3-32                   | AutoRegLib-1.3-32.jar                         | None                                     |
	| LCHIJA | betteranimationscollection2 | 1.0.2                    | BetterAnimationsCollection2-v1.0.2-1.12.2.jar | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LCHIJA | betternether                | 0.1.8.6                  | betternether-0.1.8.6.jar                      | None                                     |
	| LCHIJA | patchouli                   | 1.0-23.6                 | Patchouli-1.0-23.6.jar                        | None                                     |
	| LCHIJA | bewitchment                 | 0.22.63                  | bewitchment-1.12.2-0.0.22.64.jar              | None                                     |
	| LCHIJA | bibliocraft                 | 2.4.6                    | BiblioCraft[v2.4.6][MC1.12.2].jar             | None                                     |
	| LCHIJA | cdm                         | 0.4.1                    | cdm-0.4.1-mc1.12.2.jar                        | None                                     |
	| LCHIJA | chameleon                   | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| LCHIJA | chiselsandbits              | 14.33                    | chiselsandbits-14.33.jar                      | None                                     |
	| LCHIJA | codechickenlib              | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cooking_chef                | 1.0.0                    | cooking_chef-1.12.2-1.0.0.jar                 | None                                     |
	| LCHIJA | cookingforblockheads        | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar         | None                                     |
	| LCHIJA | ctm                         | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCHIJA | elevatorid                  | 1.3.14                   | ElevatorMod-1.12.2-1.3.14.jar                 | None                                     |
	| LCHIJA | enchdesc                    | 1.1.15                   | EnchantmentDescriptions-1.12.2-1.1.15.jar     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enderstorage                | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | engineersdecor              | 1.1.5                    | engineersdecor-1.12.2-1.1.5.jar               | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | llibrary                    | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil                      | 8.0.5                    | fossilsarcheology-8.0.6.jar                   | None                                     |
	| LCHIJA | cfm                         | 6.3.0                    | furniture-6.3.2-1.12.2.jar                    | None                                     |
	| LCHIJA | waila                       | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA | ironchest                   | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCHIJA | malisiscore                 | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                  | None                                     |
	| LCHIJA | malisisdoors                | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| LCHIJA | mantle                      | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | mightyarchitect             | 0.3.0                    | mightyarchitect-0.3.0.jar                     | None                                     |
	| LCHIJA | mobends                     | 1.2.1                    | MoBends_1.12.2-1.2.1-19.12.21.jar             | None                                     |
	| LCHIJA | naturesaura                 | 18.1                     | NaturesAura-18.1.jar                          | None                                     |
	| LCHIJA | shetiphiancore              | 3.5.9                    | shetiphiancore-1.12.0-3.5.9.jar               | None                                     |
	| LCHIJA | platforms                   | 1.4.6                    | platforms-1.12.0-1.4.6.jar                    | None                                     |
	| LCHIJA | quarkoddities               | 1                        | QuarkOddities-1.12.2.jar                      | None                                     |
	| LCHIJA | refinedstorage              | 1.6.16                   | refinedstorage-1.6.16.jar                     | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | refinedstorageaddons        | 0.4.5                    | refinedstorageaddons-0.4.5.jar                | None                                     |
	| LCHIJA | rustic                      | 1.1.7                    | rustic-1.1.7.jar                              | None                                     |
	| LCHIJA | rusticwitchcraft            | 1.0.2                    | rusticwitcraft-1.0.2.jar                      | None                                     |
	| LCHIJA | sit                         | v1.3                     | sit-1.12.2-v1.3.jar                           | None                                     |
	| LCHIJA | storagedrawers              | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar               | None                                     |
	| LCHIJA | tconstruct                  | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCHIJA | tinkertoolleveling          | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar           | None                                     |
	| LCHIJA | travelersbackpack           | 1.0.35                   | TravelersBackpack-1.12.2-1.0.35.jar           | None                                     |
	| LCHIJA | tropicraft                  | 7.1.9.115                | tropicraft-MC1.12.2-7.1.9.115.jar             | None                                     |
	| LCHIJA | tumbleweed                  | 1.12-0.4.7               | tumbleweed-1.12-0.4.7.jar                     | None                                     |
	| LCHIJA | vehicle                     | 0.44.1                   | vehicle-mod-0.44.1-1.12.2.jar                 | None                                     |
	| LCHIJA | waystones                   | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                    | None                                     |
	| LCHIJA | lemonlib                    | 1.3.0                    | lemonlib-1.12.2-1.3.0.jar                     | None                                     |
	| LCHIJA | arcaneworld                 | 0.0.11                   | arcaneworld-1.12.2-0.0.11.jar                 | None                                     |
	| LCHIJA | betterdisplays              | 1.12.2-1.0.0             | BetterDisplays-1.12.2-1.0.0.jar               | None                                     |
	| LCHIJA | immersiveengineering        | 0.12-98                  | ImmersiveEngineering-0.12-98.jar              | None                                     |
	| LCHIJA | mysticallib                 | 1.12.2-1.13.0            | mysticallib-1.12.2-1.13.0.jar                 | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
AALoadingPlugin (arcanearchives-0.2.0.25-mixins8.jar)
  
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
Backpacked (backpacked-1.4.3-1.12.2.jar)
  com.mrcrayfish.backpacked.asm.BackpackedTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 516.40' Renderer: 'NVIDIA GeForce RTX 3070/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a
	Launched Version: vivecraft-1.12.2-jrbudda-11-r6-forge
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.40, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 516.40
	OpenGlRenderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by fayer3** [comment]
likely caused by mobends, try removing it

**Comment by c0smicSalm0n** [comment]
worked thank you
