### ISSUE TITLE
[1.12.2 v5R2] Player scale is halved?

### ISSUE THREAD

**Issue by zimboptoo** [jrbudda/Vivecraft_112#22]
Windows 10, i7 7700HQ, GTX 1060, Vive, MC 1.12.2, Vivecraft V5R2.

Upon loading the game, both in the main menu and in game (tried both a new world and an existing world that worked fine in 4R3), the tracked space and all movement seems to be represented in half scale.  The floor looks like it's at about my hips, and the controller representations are about a "foot" above where they actually are, and about half the size.  When I move the controllers, they only move about half the distance in VR.  

Changing the World Scale doesn't fix it.  Once a game is loaded, I can change the World Scale and it'll make me larger or smaller in comparison to the world, but the floor and controller representations are still wrong, so I'm always hip-deep in the floor and the controllers don't track where they are in the real world.  

I tried restarting Minecraft, SteamVR, and my computer.  I redid SteamVR Room Setup, reset all Vivecraft settings, and tried several combinations of World Scale and height calibrations.  I tried re-installing V5, both vanilla and with a few mods in Forge.  None of these fixed the problem.  

I tried re-installing V4 and it works fine, as it did yesterday.  

I'm at a loss.  That no one else is reporting this problem leads me to believe that it's a weird problem on my end, maybe some obscure setting that I've changed and forgotten, but it worked (and still works) with V4, so it must be tied to a change in V5?

**Comment by jrbudda** [comment]
check your locomotion settings > walk multiplier setting, if its that its... misbehaving.

**Comment by jrbudda** [comment]
This build should restore the Walk Multiplier setting back to sanity.

[vivecraft-1.12.2-jrbudda-5-RC4-installer.zip](https://github.com/jrbudda/Vivecraft_112/files/1508833/vivecraft-1.12.2-jrbudda-5-RC4-installer.zip)

**Comment by zimboptoo** [comment]
Finally got a chance to test.  It was indeed the Walk Multiplier setting in RC2/3 (setting it in the 4-5 range is hilarious and terrifying), and it appears to be fixed in the RC4 build you linked. 

Thanks!  You're amazing!
