### ISSUE TITLE
Force Open Keyboard = GUI Insta-close

### ISSUE THREAD

**Issue by number65259** [jrbudda/Vivecraft_112#23]
With default keybinds, the VR Keyboard seemingly opens for a split second and closes right after when pressing left grip+app button. This will also close any inventory screen or mod GUI you were attempting to type in. Rebinding vrmapping_GUI Menu Button to anything other than the left appmenu will prevent inventory/gui/keyboard instaclose when opening the kb using left appbutton+grip. Not a huge problem considering the easy workaround, but the bug can hinder use of popular mods that don't auto-open the keyboard reliably (RFTools shapecard text fields are one example). Possibly related to earlier commit where ESC is being emulated with an appmenu press?

**Comment by jrbudda** [comment]
We'll look at it. The new keybind system is full of quirks.

**Comment by Techjar** [comment]
Obvious oversight on my part. Will be fixed in next build.

**Comment by jrbudda** [comment]
try dat

[vivecraft-1.12.2-jrbudda-5-RC4-installer.zip](https://github.com/jrbudda/Vivecraft_112/files/1508804/vivecraft-1.12.2-jrbudda-5-RC4-installer.zip)
