### ISSUE TITLE
[Linux/OpenVR] Instant crash when picking up controllers.

### ISSUE THREAD

**Issue by source83** [jrbudda/Vivecraft_112#24]
Like I wrongly posted in [issue #241](https://github.com/jrbudda/minecrift/issues/241).
Except, here it locks up as soon as I pick up the controllers.
I can look around with the vive, but as soon as the controllers register movement by me, it locks.
The thing is that it looks like some sort of fight between the controller avatar from steamvr and the overlay in vivecraft.
I can see them sort of fade back and forth if they were in view of the vive's render field.

(just thought of this) I could try moving the controllers while the vive is pointing in a different direction to see if it makes a difference, but I doubt it.

Since the 1.10.2 build did roughly work, is there something to gleam from it ?

**Comment by Techjar** [comment]
You are running on Linux, correct?

**Comment by source83** [comment]
crap, sorry, forgot to mention that.
Ubuntu 17.04
gtx 1070
driver vulkan(?) 387.34

**Comment by Techjar** [comment]
Yeah, this is probably some sort of SteamVR issue. Happens to me as well. It's the whole vrserver crashing randomly when controllers gain/lose tracking, though only in Vivecraft for some reason.

**Comment by source83** [comment]
Is this of any help ?
I can upload the dump file if you can look at it.

`crash_20171129031649_1.dmp[23106]: Uploading dump (out-of-process)
/tmp/dumps/crash_20171129031649_1.dmp
crash_20171129031649_1.dmp[23106]: Finished uploading minidump (out-of-process): success = no
crash_20171129031649_1.dmp[23106]: error: libcurl.so: cannot open shared object file: No such file or directory
crash_20171129031649_1.dmp[23106]: file ''/tmp/dumps/crash_20171129031649_1.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
[03:19:55] [main/INFO]: Stopping!
[03:19:55] [main/INFO]: SoundSystem shutting down...`

**Comment by source83** [comment]
Hm, "file" on the crash dump reports this: Mini DuMP crash report, 14 streams
I'm trying to find something to read it with, found a windows online minidump reader that gave a coherent output even when it's not a windows dump :D

**Comment by Techjar** [comment]
Yeah you should be taking all that over to https://github.com/ValveSoftware/SteamVR-for-Linux/issues because I haven't a clue how to interpret that stuff.

**Comment by source83** [comment]
Yeah, I'm working on a post there now

**Comment by source83** [comment]
Done, took some time to formate it as readable as I could.
[SteamVR-for-linux issue](https://github.com/ValveSoftware/SteamVR-for-Linux/issues/80)

**Comment by source83** [comment]
Since this seems to be related to SteamVR/OpenVR and not ViveCraft itself, I'm closing this issue.
