### ISSUE TITLE
Rift control oddities in 1.12.2 (forward motion with stick & trigger inputs)

### ISSUE THREAD

**Issue by Golgot** [jrbudda/Vivecraft_112#25]
Heya, 

I'm using controller-led locomotion, and bizarrely I can reverse at normal speed (down on left stick), but forward motion (up on left stick) is weirdly slow. Like barely moving. 

Also sprint (tied to the index trigger) doesn't respond.

Something to do with the Steam update maybe? (I've heard that's messing with some Rift inputs).

Thanks for all your fine work on this amazing mod! :)

(I'm getting around fine for now by pointing at my own chest ;))

**Comment by Techjar** [comment]
Yeah that shouldn't be happening. If you're on the SteamVR beta, opt-out of that, as I have heard that it is causing issues with the Rift.

**Comment by Techjar** [comment]
Oh I see what's going on, you bound the stick to forward movement. That currently doesn't work correctly, as it reads the X axis. Use joy/pad locomotion if you want to use the stick for movement. As for the sprint button, either you bound the button multiple times causing a conflict (it will be red if so), or it is working and you just don't notice (the speed increase is quite subtle in VR).

**Comment by Techjar** [comment]
I have fixed this for the next RC.

**Comment by Golgot** [comment]
Nice one cheers for the tips and the fix :)

The sprint thing is still a bit odd (I checked for conflicts, and got no rabbit icon on toolbar which suggested it wasn't kicking in). I'm just on vanilla steam vr so not that. (Will tinker with it more tonight GMT)

**Comment by jrbudda** [comment]
Give this a try. Your sprint problem is likely related, in Minecraft logic you have to be moving forward more than 80% speed for sprint to activate.

Be sure and check thru the locomotion settings as some things have changed. Ideally binding move forward/back/left/right to something with an axis should work now, tho we do recommend Joy/Pad mode if you want to go that route with the Touch joystick.

[vivecraft-1.12.2-jrbudda-5-RC5-installer.exe.zip](https://github.com/jrbudda/Vivecraft_112/files/1524806/vivecraft-1.12.2-jrbudda-5-RC5-installer.exe.zip)

**Comment by Golgot** [comment]
Excellent thanks guys, all working a treat in RC5 :)

(I've stuck with controller + custom stick bindings, but purely because the strafe x-axis is hardwired in the joypad version, and that tinges my gills a bit when I use it by mistake ;). Loving the options, means I can find my own fit :))

The sprint was def failing because I wasn't hitting the required speed. Cheers for all the help.

**Comment by jrbudda** [comment]
Actually that build I posted is super duper broken in a few places. This one has more thoroughly tested and finished options.

[vivecraft-1.12.2-jrbudda-5-RC5-installer.exe.zip](https://github.com/jrbudda/Vivecraft_112/files/1525593/vivecraft-1.12.2-jrbudda-5-RC5-installer.exe.zip)

**Comment by Golgot** [comment]
Nice one ta. (It all played nice for me, but on to the new shiny!)
