### ISSUE TITLE
Nothing rendering in the vive headset

### ISSUE THREAD

**Issue by TheBricktop** [jrbudda/Vivecraft_112#27]
I have latest release of Vivecraft 112 (v5), i7 6700 hq, 8 gb ram and gtx 965 ti (which is BARELY enough for vive but still runs something off steam),
after reducing everything to minimum I still cannot see anything on HMD (default grid only).
I dont know whats the issue with that. Mirror shows pretty decent fps.

**Comment by Techjar** [comment]
See section "The game shows up on my desktop, but not in the headset!" in the Vivecraft FAQ: http://www.vivecraft.org/faq/
