### ISSUE TITLE
Vivecraft not working on MultiMC

### ISSUE THREAD

**Issue by MrEvilGuy** [jrbudda/Vivecraft_112#29]
Hi there,

I can't get Vivecraft to work with MultiMC. I've followed your instructions on http://www.vivecraft.org/multimc/
To troubleshoot I've been using the newest version of Vanilla minecraft, but with no luck. I tried with or without a Forge installation. 
The issue is the game starts but not in VR, and there are no VR settings in the Minecraft menu, so I think it's an issue of MultiMC not detecting Vivecraft. I'm using an Oculus Rift, and have SteamVR running.

If this question is more suited to the MultiMC github page, let me know and I can repost there.

In the meantime, I'll try using an older version of Vivecraft to see if that will work.

Thank you,
Andrew

**Comment by Aceship** [comment]
from what i tried, vivecraft didnt support the newest MultiMC 5 version 0.6 yet, it supposed to works at MultiMC 5 version 0.5.2 for now

**Comment by MrEvilGuy** [comment]
Thanks for the quick reply. This is frustrating because I can't get MultiMC version 5, it just keeps auto updating to version 6!

**Comment by MrEvilGuy** [comment]
Nice! I finally got 2 instances of Minecraft (with Simple Life 2 modpack installed) to run on the same computer, one instance with VR, one instance with keyboard/mouse monitor, on the same LAN server. Didn't need MultiMC after all.

Thank you Vivecraft.

**Comment by MrEvilGuy** [comment]
Edit: Xbox 360 controller plus oculus touch, not mouse and keyboard
