### ISSUE TITLE
Roomscale Bow - Arrows Firing in the Wrong Direction

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [jrbudda/Vivecraft_112#3]
Sometimes when I'm using the roomscale bow mechanic, I'll fire an arrow and it'll veer off to the side, and keep doing it until I move. I encounter this issue almost every time I'm shooting down hordes of monsters at night. I host a private server for my friends and I (with VSE installed) and the server keeps reporting errors such as the following:

[WARNING] Wrong location! (-35, 55) should be (-35, 54), EntityTippedArrow['Arrow'/8830, l='world', x=-558.74, y=69.81, z=880.16]

I have no idea what is causing this issue. I am running the latest Vivecraft for 1.12, with Forge, on Windows 10 Pro, using an Oculus Rift + Touch controllers.

**Comment by jrbudda** [comment]
I assume this only happens in multiplayer

**Comment by AwesomeAnimationGamer** [comment]
Not sure, I've only played multiplayer so far. I'll test singleplayer soon.

**Comment by jrbudda** [comment]
It sounds like maybe some kind of anti-cheat sorta thing that wasnt in previous servers, I will take a look.

**Comment by AwesomeAnimationGamer** [comment]
I just tested through a whole night in singleplayer, it's definitely a server-only issue.

**Comment by AwesomeAnimationGamer** [comment]
Just wanted to check up on this, any luck figuring out the source of this issue?

**Comment by Techjar** [comment]
Wrong location is normally a world corruption issue. It's saying the entity exists within a different chunk than its coordinates point to.

**Comment by AwesomeAnimationGamer** [comment]
Hmm... odd. I guess it's just something I'll have to deal with. It's not really a huge deal, I can fix it by moving slightly forward/backward, and I have Infinity on my bow so it's not like it's wasting any arrows. I'm getting a new computer soon, hopefully that fixes it. Thanks!

**Comment by Techjar** [comment]
That will likely not fix it.

**Comment by Techjar** [comment]
Are you sure it's spitting that error out when you fire the arrow? Not when a chunk is loaded?

**Comment by AwesomeAnimationGamer** [comment]
So... what are you saying? Is something up with my world file?

**Comment by AwesomeAnimationGamer** [comment]
Well it usually happens around the same time I'm hunting mobs, and not anytime else. And it mentions arrow entities too, so...

**Comment by Techjar** [comment]
Well, the only time that error can occur is when loading chunks, not when new entities are added to the world. So... maybe? Can you back up your current world and test a new one to be sure?

**Comment by Techjar** [comment]
Plus that error causes the entity to be removed from the world, but you haven't mentioned any arrows disappearing, so I suspect there is in fact something buggered in your world data.

**Comment by AwesomeAnimationGamer** [comment]
I'll try that tomorrow. Also, when I said I'm getting a new computer I meant the server's moving over to the new one. Would that still not fix it? (Sorry, I don't know much about the inner workings of Minecraft lol)

**Comment by Techjar** [comment]
Yeah no, if your world data is buggered that would not be magically fixed by moving to new hardware.

**Comment by Techjar** [comment]
Not that the wrong location entities are actually a problem in and of themselves, though they can be a sign of other problems like chunks actually getting corrupted. But what I *am* saying is that the error is a red herring, and is not actually related to your main issue.

**Comment by AwesomeAnimationGamer** [comment]
Alright. Well, I guess I'll just have to live with it then. It doesn't happen constantly, it's on and off, and I can fix it by just moving a bit. It's certainly not worth scrapping the world and starting over. Thanks for your help!

**Comment by jrbudda** [comment]
I have not looked into this yet, personally.

**Comment by AwesomeAnimationGamer** [comment]
I haven't had a chance to test a new world yet, but I did get some (hopefully) valuable information: as soon as it happened I checked the time: 10:11 PM. After I got out of VR, I checked the server console and sure enough, the wrong location error showed up twice at 10:11 PM. I fired two glitched arrows before it fixed. Two arrows, two errors, same time. I hope this helps!

**Comment by AwesomeAnimationGamer** [comment]
Also, I have been noticing that the arrows are in fact disappearing. I had originally thought they weren't because after it happened for the very first time I looked around and saw an arrow sticking in the ground beside me. I know it was one of mine because it was on fire. But now I'm noticing that when they glitch, I don't hear them land. Next time this happens I will check thoroughly to see if they landed anywhere, or if they are actually despawning.

**Comment by AwesomeAnimationGamer** [comment]
Is it something that can be fixed?

**Comment by jrbudda** [comment]
Dunno yet

**Comment by AwesomeAnimationGamer** [comment]
Alright. Keep me posted. Thanks!

**Comment by jrbudda** [comment]
See if this does it. It's actually a pretty big flaw in spigot. Caused when you're standing in one chunk, but your hands are in another. Hopefully solved by deferring the arrow re-location by a tick.

[Vivecraft_Spigot_Extensions 1.12v3.zip](https://github.com/jrbudda/Vivecraft_112/files/1200885/Vivecraft_Spigot_Extensions.1.12v3.zip)

**Comment by AwesomeAnimationGamer** [comment]
This fixed it! I even tested by turning on my minimap's chunk grid and standing right at the border. Thank you so much!
