### ISSUE TITLE
Virus detection report

### ISSUE THREAD

**Issue by wuyuanyi135** [jrbudda/Vivecraft_112#30]
Hello,
I was trying to download vivecraft-1.12.2-jrbudda-5-final-r3-installer.exe but Windows Defender reported a virus: Trojan:Win32/Peals.F!cl. I am not sure if this file is modified. Can you provide the hash or md5 for validation?

**Comment by Techjar** [comment]
Unfortunately these false positives are common for some reason, probably something to do with launch4j. We don't have any control over it, so you just have to add an exception and ignore it. Here's the sha1 hash for your peace of mind: ab8c8af97969bbe1f39f56e805c71dd42054d4cc

**Comment by wuyuanyi135** [comment]
Thanks
