### ISSUE TITLE
Offhand Controller Not Visible

### ISSUE THREAD

**Issue by number65259** [jrbudda/Vivecraft_112#34]
For some reason the offhand vive controller hasn't been initializing with the game. It doesn't appear to be dependent on the remote itself. If I shut the working mainhand vive controller and power on the other, it functions as the mainhand remote and works as expected. Rebooting both controllers doesn't seem to solve the issue while in game. I've been restarting until it works - can't figure out how to reproduce reliably. I feel like it might have something to do with whether or not the controllers are on/headset is tracking when the game is started.

**Comment by unnamed7** [comment]
I have a similar issue. Since updating to v12 right controller doesn’t work. It only works while selecting settings, inventory and hot bar. All other inputs e.g drop does not work.

T

**Comment by jrbudda** [comment]
Have steamvr up and running and everything connected before starting the game, see if that helps.

**Comment by number65259** [comment]
I've been able to significantly reduce occurrence by making sure the headset isn't sleeping and both controllers are on before launching MC. There is still some occasional strange behavior, like the headset not hooking into the app at all (no tracking in MC once launched, javaw not reported in SteamVR). Recent changelogs from SteamVR indicate that there's a good chance they borked something on their end, but I'm not sure if the issues are directly related.

**Comment by jrbudda** [comment]
this should be fixed in 6-alpha-4

**Comment by number65259** [comment]
Awesome dude. Closing and leaving these here since they seem relevant. Lots of people suspect the headset initialization problem is due to a driver bug.
[One Controller Issue](http://steamcommunity.com/app/250820/discussions/0/1699415798756733033/)
[Black headset/no hook into app](http://steamcommunity.com/app/250820/discussions/0/1692659135923852656/)
[Black headset+controller issues+crashing](http://steamcommunity.com/app/250820/discussions/0/1692659769956660781/)
