### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by AireagoirSteam** [jrbudda/Vivecraft_112#35]
Hello I'm using a fresh install of minecraft and got a crash with the latest build of vivecraft.

Just thought I'd bring this to your attention in case others have the same issue as me

heres my log it mentions something about opnvr. 
[crash-2018-02-03_18.35.00-client.txt](https://github.com/jrbudda/Vivecraft_112/files/1692062/crash-2018-02-03_18.35.00-client.txt)

I'm using riftcat also just in case that has any bearing.

**Comment by jrbudda** [comment]
yea riftcat is the culprit here, this should have been fixed in one of the earlier alpha builds but it looks like i am a dummy.

**Comment by jrbudda** [comment]
try this 
[vivecraft-1.12.2-jrbudda-6-alpha7-installer.exe.zip](https://github.com/jrbudda/Vivecraft_112/files/1692213/vivecraft-1.12.2-jrbudda-6-alpha7-installer.exe.zip)
