### ISSUE TITLE
Minor typo in installer: 'recommened'

### ISSUE THREAD

**Issue by ethzero** [jrbudda/Vivecraft_112#36]
In the installer for package "vivecraft-1.12.2-jrbudda-6-alpha8-installer.exe" I spotted a tiny typo in the tool tip text for the "Profile Ram Allocation (GB)" dropdown:
"... At least 2GB is _recommened_ ..."

Thanks

**Comment by jrbudda** [comment]
Well it took hours, but I think I've got this one solved.
