### ISSUE TITLE
"Error: java.lang.VerifyError: Bad local variable type" with Forge and betterFoliage

### ISSUE THREAD

**Issue by SupraLP** [jrbudda/Vivecraft_112#39]
I just installed vivecraft and wanted to start it, just after finishing the loading screen the image is there for a few seconds, then the game crashes and gives me this error:
"The game crashed whilst unexpected error
Error: java.lang.VerifyError: Bad local variable type"
I have the mods betterfoliage and optifine installed, since vivecraft already has optifine i removed it from the mods folder, but i still get the error. I also installed vivecraft without forge, that works just fine, maybe the crash reports help identifying the problem

the newer crash report is with just betterFoliage, the older with optifine and betterFoliage
[crash-2018-03-11_08.19.11-client.txt](https://github.com/jrbudda/Vivecraft_112/files/1800144/crash-2018-03-11_08.19.11-client.txt)
[crash-2018-03-11_09.28.19-client.txt](https://github.com/jrbudda/Vivecraft_112/files/1800145/crash-2018-03-11_09.28.19-client.txt)
(open with n++/etc. for right formatting, not editor)

**Comment by jrbudda** [comment]
thank you for the report, could you post the startup full log for the latter case?

**Comment by SupraLP** [comment]
the latest.log? here ya go, tell me if you need more infos (e.g. betterfoliage.log, fml-client-#.log...)
[latest.log](https://github.com/jrbudda/Vivecraft_112/files/1800167/latest.log)


it seems like someone else had a problem with betterfoliage also on the older version: 
https://github.com/jrbudda/Vivecraft_111/issues/57
seems like betterfoliage causes some problems, i will test forge without any mods in a few minutes

**Comment by SupraLP** [comment]
ok, it's to 100% a problem with betterfoliage, without it it just works perfectly fine, just tested it

**Comment by jrbudda** [comment]
try dis. 

Someone actually reported this a month ago to betterfoliage and not me. :( https://github.com/octarine-noise/BetterFoliage/issues/169

[vivecraft-1.12.2-jrbudda-6-alpha10-installer.exe.zip](https://github.com/jrbudda/Vivecraft_112/files/1800206/vivecraft-1.12.2-jrbudda-6-alpha10-installer.exe.zip)

**Comment by SupraLP** [comment]
yes, it works, maybe you should put that fix in the regular download or a second download right beside the regular, thanks
