### ISSUE TITLE
Ability to opt item out of bow mechanics

### ISSUE THREAD

**Issue by blay09** [jrbudda/Vivecraft_112#40]
My mod Waystones adds items that use the bow action to allow similar chargeup as the bow has, but they aren't actually bows. Vivecraft still considers them bows though, which breaks the items as they're not compatible with the VR bow behaviour.

Is there a way I can mark the items so that Vivecraft ignores them, or will I have to sacrifice the chargeup feature if Vivecraft is loaded?

https://github.com/blay09/Waystones/blob/1.12/src/main/java/net/blay09/mods/waystones/item/ItemWarpStone.java#L53

https://github.com/blay09/Waystones/issues/87

**Comment by Techjar** [comment]
Yeah this isn't an easily solvable problem...

**Comment by jrbudda** [comment]
There is an option in Vivecraft to disable the roomscale bow for mod items.
