### ISSUE TITLE
[Compiling] ImportError: No module named runtime.mcp

### ISSUE THREAD

**Issue by retr0virus** [jrbudda/Vivecraft_112#44]
I downloaded the current 1.12.2 files and tried to build them (build.sh). It dies in the "recompiling" section with the following error:
Recompiling...
Traceback (most recent call last):
  File "build.py", line 248, in <module>
    main(os.path.abspath(mcp_version))	
  File "build.py", line 228, in main
    from runtime.mcp import recompile_side, reobfuscate_side
ImportError: No module named runtime.mcp

Please tell me what I can try to solve this issue. I am running the 64bit version of Arch Linux.

**Comment by jrbudda** [comment]
It's trying, and failing, to import commands from {root}\mcp940\runtime\mcp.py
Either mcp didn't get installed correctly or somethings wrong with Python on your machine.

Did you run install.bat first? Did that go okay?

**Comment by retr0virus** [comment]
No, I tried to start with the build.sh first. I now tried install.sh but it failed (404) to download the mcp940. I manually downloaded it from the site but the install.sh still fails.
First a (skipped) warning/error:
```
  Patching mcp.cfg. Ignore "FAILED" hunks
  patching file mcp.cfg
  patch unexpectedly ends in middle of line
  Hunk #1 FAILED at 171.
  1 out of 1 hunk FAILED -- saving rejects to file mcp.cfg.rej
```
Later it fails with:
```
Applying Optifine...
 Merging
  /home/user/prog/vcraft/Vivecraft_112-1.12.2-jrbudda-6/mcp940/jars/libraries/optifine/OptiFine/1.12.2_HD_U_C7/OptiFine-1.12.2_HD_U_C7.jar
 into
  /home/user/prog/vcraft/Vivecraft_112-1.12.2-jrbudda-6/mcp940/jars/versions/1.12.2/1.12.2.jar
zipmerge: target not a zip-file: /home/user/prog/vcraft/Vivecraft_112-1.12.2-jrbudda-6/mcp940/jars/versions/1.12.2/1.12.2.jar
Traceback (most recent call last):
  File "install.py", line 664, in <module>
    main(os.path.abspath(mcp_version))
  File "install.py", line 488, in main
    zipmerge( minecraft_jar, optifine )
  File "install.py", line 378, in zipmerge
    target = zipfile.ZipFile( target_file, 'r')
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/home/user/prog/vcraft/Vivecraft_112-1.12.2-jrbudda-6/mcp940/jars/versions/1.12.2/1.12.2.jar'

```

**Comment by jrbudda** [comment]
Target not a zip-file: /home/user/prog/vcraft/Vivecraft_112-1.12.2-jrbudda-6/mcp940/jars/versions/1.12.2/1.12.2.jar

That's weird, it's failing to download the vanilla game jar from mojang, likely related to it also not downloading MCP. What's the error you get with the downloads?

**Comment by retr0virus** [comment]
I copied now the 1.12.2.jar from the official client directory to the expected location. The installation continued.
But as the first failed patch the patching during the decompilation also fails and the java code seems to contain errors. It lists 100 errors... I think it starts with the use of the "do" keyword in the code:
```
== ERRORS FOUND in JAVA CODE ==

src/minecraft/net/minecraft/block/BlockSkull.java:306: error: <identifier> expected
                return IGrowable.do;
                                 ^

src/minecraft/net/minecraft/block/IGrowable.java:238: error: <identifier> expected
    public static final BlockBone do;
                                 ^

```
Also it seems not to be able to find all files:
```
Initial client recompile failed, correct source then run updatemd5
Patching Optifine merge decompile errors...
Applying Changes...
patching file net/minecraft/block/state/BlockStateBase.java
Hunk #1 FAILED at 32.
Hunk #2 FAILED at 87.
2 out of 2 hunks FAILED -- saving rejects to file net/minecraft/block/state/BlockStateBase.java.rej
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/net/minecraft/util/ClassInheritanceMultiMap.java
|+++ b/net/minecraft/util/ClassInheritanceMultiMap.java
--------------------------
File to patch: 
Skip this patch? [y] 
```
Also I would really like to compile it - is there a possibility to simply run server/client of vivecraft on a GNU/Linux system? On the download page there were only .exe-installer for Windows - nothing for GNU/Linux?

**Comment by jrbudda** [comment]
You can rename the .exe to .jar and it will run, if all you're trying to do is play it. However SteamVR is a little buggy on linux from what I'm told.

For compiling I think the problem is you downloaded the source zip from the releases page which is from January. The install scripts were heavily updated in March, update your local code from the master branch and it should work.

**Comment by retr0virus** [comment]
Thank you for the info with the old release state. I tried the current repo state and the downloading of the versions now works. There are still some (but less) patch-errors and also there were still some compilation errors.
The install process stops now when trying to call "windres":
`launch4j: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/home/user/prog/vcraft/Vivecraft_112/installer/launch4j/bin/windres": error=2, Datei oder Verzeichnis nicht gefunden`
This means "File or directory not found" - I checked the directory and there is the windres.exe file (is it trying to call it as a linux binary?) I think it should not even try to use the exe files in a Linux-environment?

I now downloaded and renamed the latest installer-exe/jars and was able to start the (currently only non-VR) profile.
We will see how the VR version (and also SteamVR) will work - I bought the HTC Vive this week (hopefully it will arrive tomorrow) - and I have no access to a Windows machine. So everything that I want to play/use with the Vive will have to run under Linux. Unfortunately it seems that most of the games have their VR support only for Windows. :-(
So I'm really glad that this project exists and that it supports also the Linux version. :-)

**Comment by retr0virus** [comment]
I have an AMD Vega 64 with the open source (mesa) drivers.
Also it seems that you were right - SteamVR makes some issues. The room setup directly exits after starting. So I cannot setup the room and am half inside the floor in the SteamVR home. :-/ Also it seems to run very unstable. Sometimes not starting the SteamVR home environment at all... Thinking if I should send the Vive back :P Maybe the new 4.16 kernel would help.

Any ideas for a workaround for the shader issue? Seems not to be working with the open source drivers?
```
$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX Vega (VEGA10 / DRM 3.23.0 / 4.15.15-1-ARCH, LLVM 6.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.0
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.0.0
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.0.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

**Comment by Techjar** [comment]
Mesa apparently doesn't support the GLSL 3.3 compatibility profile, but it does support the core profile. Try this:

Go to `.minecraft/libraries/com/mtbs3d/minecrift/<vivecraft version>`, open the jar file there as an archive. Then, modify `assets/vivecraft/shaders/mixedreality.sh` changing `#version 330` to `#version 330 core` and reinsert it into the jar. I'm not 100% sure that shader will work on the core profile, but it's worth a shot.

**Comment by Techjar** [comment]
As for the SteamVR issues, yeah, if you absolutely won't use Windows in any way, then I would recommend sending the Vive back and just putting VR on hold until SteamVR on Linux improves. Get yourself a 144Hz monitor instead, it's fantastic!

**Comment by retr0virus** [comment]
I tried the "core" profile - it didn't help. :-(
I tried to install the proprietary driver for my graphics card but it seems that there are issues with the kernel module... :-(
So for now it seems as if I cannot do anything with the Vive. :-/
I think I will try to install an older Ubuntu version where the proprietary driver may work and try it again. But I think I will not have time before the weekend for that. Still not giving up. ^^

**Comment by Techjar** [comment]
Ah yes, AMD drivers on Ubuntu. Have fun with that.

**Comment by retr0virus** [comment]
The driver were no issue. They installed and run without any problems. Unfortunately Vivecraft still was not working (at least it was not the shader issue). Also SteamVR itself was not running at all under Ubuntu. It seems the kernel is too old (on the "supported" distribution 16.04) and does not contain required fixes/functions for VR - updating and trying with a newer mesa also did not help. So it seems the 4.15.15 kernel on archlinux was overall better for SteamVR...
In the meantime I tried the 4.16 of the test repository of archlinux with the 18 mesa. It did not help for SteamVR - still no room setup.

Since two or three days the 4.16 kernel and 18 mesa are in the "stable" part of  archlinux. Finally I am able to run the room setup with it. :-)
Unfortunately it seems that there is more or less exactly one game that runs in VR at all under Linux - "The Talos Principle VR". I tried some other games and even purchased some - but none of them started the VR mode - only 2D. :-(

So I really hope to get Vivecraft running somehow. Is there a possibility to remove some of the shaders or functionalities that use features that are not supported in the open source mesa drivers?
At the current state it seems not to be possible to run Vivecraft without proprietary drivers and without a Nvidia GPU (or at least it seems not to be possible to run SteamVR with any proprietary AMDGPU-PRO driver on the "supported" systems and so with not enough shader support)?

**Comment by Techjar** [comment]
What if you change the `#version 330` to `#version 130` in the aforementioned file, instead of adding `core`?

**Comment by Techjar** [comment]
Okay, you should be able to dummy out the mixed reality shader and allow the game to continue running. The mixed reality feature won't work of course (you'll just get a black mirror window in that mode), but if you didn't care about that then it doesn't matter. The rest of the game will be fine as the shader is only used to draw the mixed reality mirror display.

Replace the whole mixedreality.fsh with this code:
```glsl
#version 130
uniform vec2 resolution;
uniform vec2 position;
uniform sampler2D colorTex;
uniform sampler2D depthTex;
uniform vec3 hmdViewPosition;
uniform vec3 hmdPlaneNormal;
uniform mat4 projectionMatrix;
uniform mat4 viewMatrix;
uniform int pass;
uniform vec3 keyColor;
uniform int alphaMode;
out vec4 out_Color;
void main(void) {
	out_Color = vec4(0, 0, 0, 1);
}
```
