### ISSUE TITLE
Chat closes immediately after opening 1.12.2v6r3

### ISSUE THREAD

**Issue by DAgility** [jrbudda/Vivecraft_112#45]
I try to open my chat from the menu and it will close immediately. It worked only once.

**Comment by DAgility** [comment]
Nope!

**Comment by DAgility** [comment]
This is still a problem.

**Comment by DAgility** [comment]
Alright thank you!

**Comment by jrbudda** [comment]
So fixing this required writing our entire own new keyboard, which is now done. Thanks Valve!

**Comment by DAgility** [comment]
Lmao, thanks volvo
