### ISSUE TITLE
Crashing in MacOS high Sierra

### ISSUE THREAD

**Issue by moimart** [jrbudda/Vivecraft_112#46]
Hi,

I'm able to make the launcher find the libopenvr_api.dylib (I used the one in the repo for osx32). The game launches showing the MOJANG title for a while till it finally crashes. Is it because of a mismatch of versions in the libraries? I've got SteamVR and some other games working flawlessly.

Thanks!

Br,
Moises

**Comment by Techjar** [comment]
I didn't even know SteamVR ran on MacOS. I'll need to see latest.log from .minecraft/logs

**Comment by moimart** [comment]
[latest.log](https://github.com/jrbudda/Vivecraft_112/files/1958108/latest.log)

Attached

**Comment by moimart** [comment]
By looking at the log it looks like minecraft only uses GL 2.1 and the VR Shaders are trying to use 3.3 core. it might be a mac issue

**Comment by Techjar** [comment]
How old is this machine? What GPU does it have?

**Comment by Techjar** [comment]
Also, you can try this build: https://cdn.discordapp.com/attachments/195502278508150784/438111729029742593/vivecraft-1.12.2-jrbudda-7-alpha3-installer.exe

**Comment by moimart** [comment]
It's a 2017 macbook pro with a radeon vega 64 (eGPU). I believe that minecraft does not create the GL context with CORE profile so it reverts back to 2.1. That would make the VRShaders not to compile (from what I see in the logs)

**Comment by moimart** [comment]
It indeed works! Really cool! Thanks!

**Comment by Techjar** [comment]
I technically could fix that shader to work on the core profile, but it's just for mixed reality mode so I don't really care enough to bother right now. Perhaps eventually.
