### ISSUE TITLE
In game virtual keyboard is not working for me on 1.12

### ISSUE THREAD

**Issue by legolas141** [jrbudda/Vivecraft_112#47]
I have just recently installed vivecraft and I love the mod, but I can't for the life of me find out how to get the virtual keyboard to pull up.  

I own a rift and am using the latest version of java.  I am not using steamvr beta.  I haven't been able to find any good information on this topic through several days of searching.  I can't get the keyboard to even appear temporarily.  I have tried clicking in the text box as well as the button combo listed on the website for the touch controllers (as well as just about every other button combination in case it had been changed). I also haven't remapped the touch controls yet even though I do want to change them around.

Is there a list of potential things that could cause the keyboard to not show up? At first I thought maybe steam had installed the beta version of steamvr but when I checked, I wasn't opted in to the beta.  I really love this version of the game but not being able to pull up the digital keyboard really limits the functionality of it as I can't navigate item lists or type in any textbox in a menu.

**Comment by legolas141** [comment]
I should also note that I am new to VR as I have only had the rift for about a month or so and have only played a few things, so I am still not very familiar with the way everything works together.

**Comment by legolas141** [comment]
Yeah I’ve tried that as well

**Comment by Techjar** [comment]
What GUI is this in?

**Comment by Aceship** [comment]
Have you tried using steam vr keyboard in steamvr, outside of vivecraft ?

**Comment by legolas141** [comment]
any gui as far as i can tell.  i got it to work briefly earlier but now it isnt letting me select the text box with the trigger, but the keyboard is still appearing so that is some progress at least.

**Comment by jrbudda** [comment]
The steamvr keyboard is going in the dumpster and being set on fire. See #45
