### ISSUE TITLE
Problem with Nolo VR controller mapping

### ISSUE THREAD

**Issue by k3nnny** [jrbudda/Vivecraft_112#5]
Hi!

I know Nolo is not a native vr stuff but I hope it will be usable for this great mod.
It's kinda working. Feels like the game detect it as oculus controller because just the teleport and the right trigger working. But stepping on the hotbar, select stuff, placing doesn't work or very buggy.
Every other game I tried so far (around 30+ game) worked perfectly. Controllers are detected as vive controller, mapping was fine. I tried to remap but nit working yet.
Any idea about this?

**Comment by jrbudda** [comment]
could you provide your latest.log file from .minecraft/logs so i can see how the controller appears to OpenVR? thanks.

**Comment by k3nnny** [comment]
Good point.
I will get it after work.

**Comment by k3nnny** [comment]
I have some progress.
I managed to map some buttons, now the inventory, hotbar stepping, place block, attack working.
Looks like the mod can't make difference between button touch and press. So when I map the hotbar stepping next and prev to touch pad left and right it just stepping randomly. I will continue the testing.
Here is my log hopefully this contain what you need.
https://pastebin.com/FbuWqDwJ
Btw the current setup is:
Riftcat, Nolo Vr (just to be clear not a dedicated HMD but the display, and head tracking is fine)

**Comment by jrbudda** [comment]
just to be clear, when you go into the controller button mapping do you get things like TOUCHPAD_UL, LEFT_GRIP, etc.. (Vive buttons) or JOYSTICK_LEFT, LEFT_BUTTON_Y etc... (Oculus buttons)

**Comment by k3nnny** [comment]
The JOYSTICk one. Is there any way to change the detection? Most of the games detect the controllers as Vive (it should work as vive controller) but the games what detect it as Oculus controllers the game there is buggy or not fully working.
Also I used the pseudovive so the steamvr itself detect it as a vive hmd and controllers. (refering to steamvr diagnostics)

**Comment by jrbudda** [comment]
yea we go off the Manufacturer info, if its 'HTC' we call it a vive, anything else we assume is oculus. I guess we'll have to fiddle with that logic. Yours seems to just be blank.

**Comment by MCWithMC** [comment]
hey k3nnny, I found this that you can try https://github.com/schellingb/PseudoVive If you need help with installing this I might be able to, but I don't have my VR setup right now so I cannot test it myself. It should make your NOLO appear to OpenVR/the game as Vive controllers.

**Comment by k3nnny** [comment]
@MCWithMC hey! Thanks for the idea. I already tried that, well it's installed since I got my rig. The steam vr diagnostics says it's a HTC device (hmd and cotntrollers)
There is another game which detects Nolo as Oculus controller that's Dead Effect 2 VR. It's unplayable because of the mapping and not even act like Vive controllers.
I'm trying other ways to force games to detect it as Vive. No luck yet :D

@jrbudda Do you have any option/file (.ini or something) to manually set the controller type in the mod? Maybe change between Vive and Oculus only mapping?

**Comment by Techjar** [comment]
There currently is not, but we could add one.

**Comment by k3nnny** [comment]
@Techjar That would be awesome!

**Comment by Techjar** [comment]
I've added the option, here's the build. Run the game first to generate the config, then edit optionsviveprofiles.txt and set forceHardwareDetection to 1.

[vivecraft-1.12-jrbudda-1-installer.exe.zip](https://github.com/jrbudda/Vivecraft_112/files/1204178/vivecraft-1.12-jrbudda-1-installer.exe.zip)

**Comment by k3nnny** [comment]
Awww cool! Many thanks for that. Will try after work!

**Comment by k3nnny** [comment]
Sorry for the late response. You know holidays and stuff.
It working perfectly!
We can close this issue.
