### ISSUE TITLE
Not really important, but...

### ISSUE THREAD

**Issue by Chimera245** [jrbudda/Vivecraft_112#50]
Whenever a Vive wand goes to sleep from inactivity, (like if I pause the game and take off the headset to go to the bathroom or got eat something) the in-game hand, and any held item will sometimes be spinning in place. It'll slowly trace a circle about three feet across.

It doesn't really harm anything, and it's actually kind of amusing.

And since it stops when you turn the controller back on, it would probably be a really low priority thing to fix.

But I figured there was the chance that this could be an indication of some other, deeper problem that you programmer-types would understand, so I thought I'd report it, just in case.

**Comment by jrbudda** [comment]
Nah normal behavior when the rotation matrix goes to all 0's. Not an indication of any underlying problem other than us not doing anything more clever detecting it.
