### ISSUE TITLE
Better questing all fucked up

### ISSUE THREAD

**Issue by Kuktar** [jrbudda/Vivecraft_112#51]
So a really big part of the continuum modpack from team FTB is the questing aspect of progression. Without the questbook it is possible to continue but with all the expert mode recipes it will be nearly impossible to do it efficiently.

The big issue is that the quest gui does not show up properly i am attaching some screenshots to show an example.

https://imgur.com/a/8N8Hu55

there is an album with pictures that should help explain my issue. Thank you.

**Comment by Techjar** [comment]
Have you tested it on the latest release?

**Comment by Kuktar** [comment]
@Techjar
Collaborator
Techjar commented 6 days ago
Haha what the fuck, that is some seriously messed up rendering. I don't even know where to start to debug this.

 @Kuktar
  
Kuktar commented 6 days ago
Ya i am not sure either. i did mess with the mods internal settings. the defualt setting for the gui is set at -1 wich meens fullscreen.

I tried 10. 50, 200, 400

on 400 it takes up half the screen and more of the texts shows up but its still unusable

 @Techjar
Collaborator
Techjar commented 6 days ago
For the record, it's not supposed to have borders of grass, stone and bedrock, right?

 @Kuktar
  
Kuktar commented 6 days ago
my settings are grass theme. the ones i pulled from the interwebs is using a diffrent theme

 @Techjar
Collaborator
Techjar commented 6 days ago
Oh ok, so it's just the screwed up box clipping.

 @Kuktar
  
Kuktar commented 6 days ago
https://imgur.com/a/scALe2m

there is what it lookse like with menue background turned on. the same i believe.

 @Kuktar Kuktar closed this 35 seconds from now
@Kuktar
  
Kuktar commented a minute from now
not sure why i opened this on the 110 issue tracker. will reopen on 112

**Comment by Kuktar** [comment]
Yes I did. I'm on vr 7 from yesterday

**Comment by Techjar** [comment]
Huh, well someone else in Discord said BetterQuesting was working fine for them. Maybe this some weird interaction with BetterQuesting, Vivecraft and another mod.

**Comment by Kuktar** [comment]
ok let me reset my better questing and see if it helps

**Comment by Kuktar** [comment]
i am getting assistance from betterquesting dev he did confirm its some clipping issues. so i will close the issue here.

**Comment by Kuktar** [comment]
get this if i empty the modpacks resource folder it fixes better questing. FTB continum comes with custom main menue and that mod uses a  root folder called resources that has jpgs in it. anyways only with vivecraft for some odd reason with that resource folder popultated it breakes better questing but when i empty it better questing works just fine.

**Comment by jrbudda** [comment]
with JUST betterQuesting and this /resources folder with the jpegs its broken? or with the manimenu mod installed as well? Does any picture break it? or what about other types of files?

**Comment by Kuktar** [comment]
Let me try those two scenarios and let you know i will start recording right now.

**Comment by Kuktar** [comment]
https://www.youtube.com/watch?v=C1NntHxjL60&feature=youtu.be

in the video i demonstrate what i have seen. If i removed custommainmenu then betterquesting works fine.

if i remove the resource folder then betterquesting works fine. it seems with vivecraft somehow they dont like eachother. this issue does not happen when i am using 2d minecraft.

**Comment by Kuktar** [comment]
ps:the video might take an hour from now to render
