### ISSUE TITLE
Huge Huge update when forge forge:1.12.2-14.23.3.2702 updated to forge:1.12.2 - 14.23.4.2705

### ISSUE THREAD

**Issue by Kuktar** [jrbudda/Vivecraft_112#52]
i am unsure if there were major changes when forge updated but there is one very very huge mod that depends on the new version. im talking about a mod that has about 5 million total downloads... its called enderstorage / shetiphiancore mod.

I know vivecraft just got a huge update 5 days ago to version 7 but how hard would it be to include the new forge?

Thank you for the consideration and let me know whats up, i know money talks :P

**Comment by Kuktar** [comment]
K trying it now. I will let you know what happens. Steak dinner on me if it
works

**Comment by jrbudda** [comment]
note that it's .4.2705, up from .3.

I did try building against that and it loads, the bug fixed in 2705 seems kinda major.

**Comment by Kuktar** [comment]
Wait you mean you have a 4.2705 vivecraft jar?

**Comment by jrbudda** [comment]
yea i just posted one in discord

**Comment by Kuktar** [comment]
holy shit i could kiss you right now. i have techjars paypal so i sent him a steak dinner for helping me 2 days ago what is yours?

also look at the fixes.

Changelog:
Build 2705:
	bs2609: Fix crash from search tree processing invalid recipes (#4942)

Build 1.12.2-14.23.4.2704:
	LexManos:
		Fix names in JSON annotation data not matching expected format. Closes
		#4953

Build 1.12.2-14.23.4.2703:
	LexManos:
		Add potential support for models defining 'vanilla like' rotations in
		Forge's Modified Blockstate format.
	LexManos: Bump version in prep for new RB.

**Comment by Kuktar** [comment]
not to mention now i can update ender storage. it got an update after its last update that was in 2017! they edded more stuffs

**Comment by Kuktar** [comment]
thank you for the 2705 build it works
