### ISSUE TITLE
Can't download Optifine 1.12.2 HD U D3

### ISSUE THREAD

**Issue by gradientxd** [jrbudda/Vivecraft_112#54]
the initial installer for vivecraft 1.12.2 couldn't install optifine, so I downloaded it manually, and when I tried launching vivecraft it couldn't start due to not being able to download optifine. can you help with this?

**Comment by jrbudda** [comment]
this is usually caused by temporary web outages. The installer does suggest installing it manually but you have to rename some files and its all quite a mess, best to just try again later.
