### ISSUE TITLE
Buildcraft Engines/Quarry/Mining Well Causes Onion Effect

### ISSUE THREAD

**Issue by GeorgeBusche** [jrbudda/Vivecraft_112#57]
Upon placing a buildcraft engine, quarry, or mining well, the game seems to "drag" across the screen, almost like stamping an image 100 times across the screen following the path of my head. Sorry for such an odd description, but I honestly don't know what to call the issue. No other blocks seem to cause this issue. I've attached a screenshot below of the issue. 
![2018-06-10_20 34 15](https://user-images.githubusercontent.com/40153081/41208176-3d667312-6cee-11e8-84e6-d4b205348d80.png)

Here is a list of mods I'm running. No other mods produce this issue.
![screenshot 1](https://user-images.githubusercontent.com/40153081/41208177-42ee6b0a-6cee-11e8-868f-de929793cba5.png)

I'm using Minecraft Version 1.12.2 with Forge, version 7 of Vivecraft, and the latest version of Buildcraft.

**Comment by jrbudda** [comment]
Could you also provide a latest.log file from when this is happening?

**Comment by GeorgeBusche** [comment]
[latest.log](https://github.com/jrbudda/Vivecraft_112/files/2091459/latest.log)

**Comment by jrbudda** [comment]
its not doing it for me. Does it do it for you just using Buildcraft and no other mods?

https://gyazo.com/537785bce952e2d91236c4453be9c12c

**Comment by GeorgeBusche** [comment]
Yeah, it does it when I've only got buildcraft installed. Btw, which minimap mod is that?

**Comment by GeorgeBusche** [comment]
Reinstalled minecraft and vivecraft and buildcraft. Works fine when only using buildcraft, I'll add my mods one at a time and see what causing the issue.

**Comment by jrbudda** [comment]
Was that a clean install of minecraft? it could be caused by a graphic setting as well

**Comment by GeorgeBusche** [comment]
Yes, clean installation of everything. I've added nearly every mod and haven't run into any problems yet.

**Comment by GeorgeBusche** [comment]
If one turns on Fast Rendering or Fast Math (which I assume are options with Optifine) the issue occurs. I know nothing about programming, but I'guess the Fast Rendering or Fast Math doesn't allow for Minecraft to properly handle the load those particular blocks add to running the game.

**Comment by Techjar** [comment]
I would be perfectly okay with just disabling these options entirely in that case.
