### ISSUE TITLE
[Request] Allow locomotion by external controller for generic VR Treadmill support

### ISSUE THREAD

**Issue by SirIntellegence** [jrbudda/Vivecraft_112#58]
I assume (I haven't checked though) that most VR treadmills have an option to output the user's movement as a joystick on an additional controller. Adding this feature would expand the number of VR treadmills a user could use with ViveCraft and I can use it for exercise.

**Comment by jrbudda** [comment]
Minecraft does not have generic controller support and adding it is not in the current scope of Vivecraft. tho I believe most of these treadmills can do WASD output which should work already.

**Comment by SirIntellegence** [comment]
True, but I tried with WASD output and was still unable to move. I have fallen back on the "walk in a direction and push the stick in that direction" method for the time being.
