### ISSUE TITLE
Minecraft launcher is not running, but installer says it is

### ISSUE THREAD

**Issue by revjtanton** [jrbudda/Vivecraft_112#6]
I've run the launcher once as per instructions however the installer says the launcher is running.  It is not running.  
![image](https://user-images.githubusercontent.com/6391564/28855935-04e85f22-770e-11e7-813a-3eea342ea939.png)

**Comment by Techjar** [comment]
That's not an error saying the launcher is running, it's merely a warning that you should ensure the launcher is closed.

**Comment by revjtanton** [comment]
The launcher wasn't open.  The computer was restarted, the launcher was definitely not open or running in any way, yet it perpetually insists that it is.

**Comment by jrbudda** [comment]
We know. The installer does not 'detect' the launcher is running, it's just a reminder.

**Comment by xmastersrule** [comment]
i have the same proplem 
it says the same but it wont show the installe button
