### ISSUE TITLE
A few ideas for this project

### ISSUE THREAD

**Issue by CNKManga** [jrbudda/Vivecraft_112#61]
here are some of my ideas:
my first idea is adding a checkbox called 'this is a multimc instance' into the installer for multimc users like myself
my second idea is a checkbox that when unchecked won't include optifine for supporting mods that crash when optifine is found, also for the installer
my third idea is make a sponge plugin for people using the spongeforge mod in their server / client
again, these are just some of the improvements/ideas i think would improve this project

**Comment by Techjar** [comment]
We don't need a checkbox for MultiMC, as you just point it at your MultiMC install folder and it detects it.
OptiFine cannot be removed from Vivecraft as it is heavily integrated into the codebase.
We wouldn't be opposed to a Sponge plugin, but it's not high on the todo list.

**Comment by CNKManga** [comment]
oh, okay. just wanted to mention these items
