### ISSUE TITLE
[Request] Option(radio buttons) for Latest and Latest Recommended Forge?

### ISSUE THREAD

**Issue by Kzitold** [jrbudda/Vivecraft_112#69]
This one, I'm quite sure should be possible (considering I've done it in Powershell.) You can leave your recommended version as the default, but would like the option for Latest and Latest Recommended Forge when "Custom Forge Version" is selected.

**Comment by Techjar** [comment]
We don't officially support versions of Forge besides the default, as the code is integrated into Vivecraft via reflection. We can't guarantee different versions will work, so it will be left as a version string and treated as an advanced feature.
