### ISSUE TITLE
[Request] Automate the Forge installer.

### ISSUE THREAD

**Issue by Kzitold** [jrbudda/Vivecraft_112#71]
If you're gonna auto-download and open the Forge installer, please go all the way and automate install client.

I know it's possible. I've done it myself with Powershell.

**Comment by Techjar** [comment]
There's no command line parameters to the installer, so we can't do this.

**Comment by Kzitold** [comment]
But with some simple file manipulation, the files from --installServer can be used for client.

Don't remember the details, but the PS script is in my updater.

https://github.com/Kzitold/Minecraft-updater/blob/master/Update/scripts/Forge.PS1

**Comment by Kzitold** [comment]
I don't know Python yet or whatever code this is.

**Comment by Techjar** [comment]
Installer.java is what you want to look at.
