### ISSUE TITLE
Vivecraft LAN Hosting Wipes Player NBT

### ISSUE THREAD

**Issue by CandiceJoy** [jrbudda/Vivecraft_112#73]
Title says it all really.  Every time someone dies or reconnects, player NBT gets wiped.  Everlasting abilities loses all your abilities, Thaumcraft doesn't let you right-click a bookshelf with salis mundis to get a thauminomicon, etc etc etc.  It looks like it wipes all player nbt for all players on death and disconnect/reconnect.  Haven't tested any environment except Open to LAN.

**Comment by jrbudda** [comment]
I think this was fixed in 1.12.2r7v7 for the VR client, and 1.12.2v8r5 for the non-vr client.
