### ISSUE TITLE
[Crash] [Mod incompatibility] [1.12.2] Crash with Astral Sorcery 

### ISSUE THREAD

**Issue by aking4125** [jrbudda/Vivecraft_112#75]
Using the latest forge, Astral Sorcery and Vivecraft. The game crashes. It doesn't generates a crash report. But using the game output. I saw this string of text: https://pastebin.com/QtjpxdfE

I'm not sure which of the log files I should be uploading. Should I also report this to the Astral Sorcery github issues page and link back here?

**Comment by Techjar** [comment]
That'd be because we removed all the code from `EntityRenderer.getMouseOver()`. I'll see later if we can reintroduce it without changing any behavior, though whatever AS is trying to do in there isn't going to work.

**Comment by jrbudda** [comment]
[vivecraft-1.12.2-jrbudda-7-r6-installer.zip](https://github.com/jrbudda/Vivecraft_112/files/2546831/vivecraft-1.12.2-jrbudda-7-r6-installer.zip)
try

**Comment by aking4125** [comment]
Just tested it and it's still crashing with Astral Sorcery. No crash report is created. I think this log file contains the information to the crash.

[latest.log](https://github.com/jrbudda/Vivecraft_112/files/2547048/latest.log)

**Comment by Techjar** [comment]
Yeah that one was broken, we fixed that and got another issue.

**Comment by jrbudda** [comment]
[vivecraft-1.12.2-jrbudda-7-r6-installer.exe.zip](https://github.com/jrbudda/Vivecraft_112/files/2550786/vivecraft-1.12.2-jrbudda-7-r6-installer.exe.zip)
I think its actually fixed now

**Comment by aking4125** [comment]
We're getting a different crash. The game now loads all the way but once it touches the menu. It crashes with this crash 
[crash-2018-11-05_20.56.11-client.txt](https://github.com/jrbudda/Vivecraft_112/files/2551322/crash-2018-11-05_20.56.11-client.txt)

**Comment by jrbudda** [comment]
uhh, was this mod pack working before you update astral sorcery? cause that looks like another mod conflict, not sure which

**Comment by aking4125** [comment]
Looking into it now cause it's crashing period now since the build 4 hours ago. Let me try the R5 version and re-work it again.

**Comment by aking4125** [comment]
There's some type of Conflict with ViveCraft, Randompatches and VanillaFix that caused the above crash. But as far as I can remember, I had Randompatches and Vanillafix on this pack before. The only mod in my pack that caused problems was Astral Sorcery. I made zero config changes to those two mods and even regen the config so I don't know how that cause the crash now.

**Comment by aking4125** [comment]
But with all that said, as that's a different issue entirely. Astral sorcery seems to be working.

**Comment by jrbudda** [comment]
this is actually fixed now, assuming randompatches isnt out of date
