### ISSUE TITLE
Vivecraft oculus 1.12.2 crashes on startup

### ISSUE THREAD

**Issue by Smashmaster52** [jrbudda/Vivecraft_112#78]
I've gotten a oculus rift and wanted to play minecraft in vr without buying the minecraft bedrock edition. Therfore using the java version. I decided to try out vivecraft version 1.12.2 however, whenever i try to start it it crashes suddenly. I have added the crash report. Btw, i have also tried restarting my computer, deleting the .minecraft and removing different files. Nothing worked. Heres a run after deleting the .minecraft.

Components:
8gb RAM
I5 4440
RX580 8gb
Windows 10 x64
[crash-2018-12-05_13.12.46-client.txt](https://github.com/jrbudda/Vivecraft_112/files/2648760/crash-2018-12-05_13.12.46-client.txt)

**Comment by Espergium** [comment]
It says it's running out of ram when you launch. Your log says you're using about 5.8 of your allocated 6. Try 5 gigs or even 4.

**Comment by Smashmaster52** [comment]
Thanks for the reply. I tried using 4gb ram, however the same happened.

**Comment by Smashmaster52** [comment]
This is also the only thing i see after the crash: 
![image](https://user-images.githubusercontent.com/45627906/49527356-04036a80-f8b2-11e8-851b-772c7f2ae81d.png)

**Comment by Smashmaster52** [comment]
I tried 2gb as well.. Here's the crash report to that as well:
[hs_err_pid10444.log](https://github.com/jrbudda/Vivecraft_112/files/2649601/hs_err_pid10444.log)

**Comment by Espergium** [comment]
Try changing your launcher to use 1 gig minimum, and 4 (or 6) maximum.

**Comment by Smashmaster52** [comment]
Did not work either..:
![image](https://user-images.githubusercontent.com/45627906/49532455-d4a62b00-f8bc-11e8-8b3f-503c1dd9e2da.png)

**Comment by Espergium** [comment]
First: Start without the ram arguments. Erase those two. The crashes are throwing an error of you running out of memory.

If you need the ram values then invert them later. Xmx is maximum, Xms is minimum. As-is you have told it to run a max of 1 with a minimum of 4. If configured improperly it crashes with a different error.
If you're running vanilla you probably don't need these.

**Comment by Smashmaster52** [comment]
Thanks alot, finally worked! Did not know how to change the memory settings. Sorry for the bother.
