### ISSUE TITLE
[Request] Allow Rebinding Radial Menu Alt Button

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [jrbudda/Vivecraft_112#79]
The radial menu is a real lifesaver when it comes to playing on a modded server. However, my preferred locomotion includes binding "Walk Backwards" to the left hand grip on the Touch controller, which means in order to access the alternate set I have to constantly move backward. Is there any way to allow rebinding this menu, or at the very least allow quick pressing to toggle the alternate set?

**Comment by jrbudda** [comment]
I dunno if we fixed this before but the new SteamVR Input version has a bindable key in the Advaanced settings for rebinding this action. It's called Keyboard Shift
