### ISSUE TITLE
no way to install on macos or linux?

### ISSUE THREAD

**Issue by Redd56** [jrbudda/Vivecraft_112#80]
... single request make the installer for the client a jar file like optifine... thats it... id like to actualy use it but unfortunately someone had the idea to make it into an exe file

**Comment by jrbudda** [comment]
it is a jar, rename it to .jar

**Comment by Redd56** [comment]
... wow..

**Comment by jcc10** [comment]
Could you just start having .jar uploads or a note on the release pages that linux can rename to .jar?

That would be the best way to avoid confusion.
