### ISSUE TITLE
update to the latest optifine

### ISSUE THREAD

**Issue by Redd56** [jrbudda/Vivecraft_112#81]
please

**Comment by Espergium** [comment]
This isn't a simple 'click to update' thing. Optifine is used as a core dependency and each version change would require a rebuild from the bottom. It's not a fast and easy process.

For now the version provided with the latest installer works fine.

**Comment by Redd56** [comment]
unfortunately it doesnt work with cubic chunks... which requires e2 and the latest forge... which is one of the mods i love, 
third mod to work on.. check...
welp im gonna have to learn java rip me

**Comment by Techjar** [comment]
https://cdn.discordapp.com/attachments/195502278508150784/521071042333245440/vivecraft-1.12.2-jrbudda-7-r8-installer.exe

Hasn't been tested much, may or may not be spectacularly broken.

**Comment by Redd56** [comment]
got a non vr version so i can test it since i dont have a headset yet? also bungee... how do i9 get it to work with that...
