### ISSUE TITLE
[1.12.2 Modded] Unable to Use OpenBlocks Elevators

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [jrbudda/Vivecraft_112#82]
During gameplay on my modded server tonight I discovered that jumping and sneaking to use the elevators from OpenBlocks is not working in VR, even if I use controller keybinds to perform these actions. Please let me know if there is a way to get this working, as the OpenBlocks Elevators are very useful in base design. Thanks!

**Comment by Techjar** [comment]
We're aware of this, but unsure what's causing it, as crouching still works.

**Comment by AwesomeAnimationGamer** [comment]
Hmm... good to know. I'll work around it for now. I would just like to note that neither action was working for me tonight.

**Comment by jrbudda** [comment]
This is fixed in 1.12.2 v7r11
