### ISSUE TITLE
[Request] Non-pop out "Wrist" GUI

### ISSUE THREAD

**Issue by ZwipZwapZapony** [jrbudda/Vivecraft_112#84]
_Disclaimer: I have not yet played Vivecraft, but I have read about it and seen a few videos of it, and I intend to play it eventually._

As far as I know, there are 3 "HUD modes" in Vivecraft. One that has the GUI above the off-hand ("Hand"), one that has it on the "inside" of the off-hand-arm ("Wrist"), and one that has it locked to the head ("Head").

The second option, "Wrist", apparently has the HUD right along the arm, but makes it "pop out" if you look at it from an angle.

I would personally like the HUD to be along the arm as in the "Wrist" option, but I don't want it to "pop out" if I look at it.

So therefore, I'd like to request a HUD mode that stays along the arm like with the "Wrist" option, but just stays there permanently without ever "popping out" at you. (This could possibly be called "Arm"?)

**Comment by ZwipZwapZapony** [comment]
While it may only "pop out" if I face my head directly at it, I'd still prefer an option to have it not "pop out" at all. (But as I haven't actually personally tried it out, I can't say for certain how annoying I find it to be when it does "pop out". I just know that an option would be nice.)

**Comment by Espergium** [comment]
The pop up allows you to use the "touch" interaction with your hotbar.

**Comment by jrbudda** [comment]
This is added in the latest prerelease, b6

**Comment by jrbudda** [comment]
hey we did this one
