### ISSUE TITLE
[1.12.2 forge] MultiMC: "Some artifacts marked as 'local' are missing their files"

### ISSUE THREAD

**Issue by ylluminate** [jrbudda/Vivecraft_112#86]
I attempted to follow the MutiMC [path for installation](http://www.vivecraft.org/multimc/) and hitting a bit of a wall:
```
MultiMC version: 0.6.3-1285

Minecraft folder is:
C:/games/MultiMC/instances/1.12.2/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_191, using 64-bit architecture.

Instance update failed because: Some artifacts marked as 'local' are missing their files:
C:/games/MultiMC/instances/1.12.2/libraries/minecrift-1.12.2-jrbudda-7-r7.jar
C:/games/MultiMC/instances/1.12.2/libraries/OptiFine-1.12.2_HD_U_D3.jar

You need to either add the files, or removed the packages that require them.
You'll have to correct this problem manually.
```

So just to walk through the installation process I followed:

1) New instance:
![instance](https://cl.ly/b11210933189/Image%202018-12-25%20at%209.53.26%20PM.png)

2) Edit instance (used "starred" Forge version number "14.23.5.2768") & Launch to download and test initial setup with Forge:
![launch](https://cl.ly/25295890e150/Image%202018-12-25%20at%209.55.39%20PM.png)

3) It downloads and launches fine:
![launched](https://cl.ly/b18def8ded5e/Image%202018-12-25%20at%209.57.29%20PM.png)

* Close MultiMC out entirely.

4) Download, run & install `vivecraft-1.12.2-jrbudda-7-r7-installer.exe`:
![installer](https://cl.ly/3d13a7996803/Image%202018-12-25%20at%2010.02.14%20PM.png)

Says "Installed successfully!. MultiMC Instance: C:\games\MultiMC\instances\1.12.2"

5) I then re-open MultiMC and attempt to launch instance `1.12.2` and get the error:
```
Instance update failed because: Some artifacts marked as 'local' are missing their files:
C:/games/MultiMC/instances/1.12.2/libraries/minecrift-1.12.2-jrbudda-7-r7.jar
C:/games/MultiMC/instances/1.12.2/libraries/OptiFine-1.12.2_HD_U_D3.jar

You need to either add the files, or removed the packages that require them.
You'll have to correct this problem manually.
```

FYI, when I do go into the Edit Instance function and check Version info, I see the following:
![version info](https://cl.ly/e2e45c78853d/Image%202018-12-25%20at%2010.09.39%20PM.png)

Conversely, the thing that bothers me is that I never see this version info as per the image on the [multimc](http://www.vivecraft.org/multimc/) page:
![supposed_to_be](http://i0.wp.com/www.vivecraft.org/wp-content/uploads/2017/11/b2766beeeae08a3e309f916caae6bece.png?w=559)

Any thoughts?  Am I missing something?

**Comment by jrbudda** [comment]
This was caused by a change to multimc, the vivecraft installer has been updated to account for it.

**Comment by ylluminate** [comment]
So @jrbudda should I use 113 or 112 and do I need to build this from the repo vs using a release download (I'm suspecting I need to rebuild from the repo as I'm guessing the updates you make probably don't propagate in some fashion on the installer via a server)...

**Comment by jrbudda** [comment]
Don't build anything from the repo unless your intention is to contribute to development. Everything is released.

**Comment by ylluminate** [comment]
Hmm, so from what I'm understanding you're saying that https://github.com/jrbudda/Vivecraft_112/releases is the right updated installer you're referring to having fixed above, however the last release for this is from May.  What am I missing here in terms of understanding how it's updated?

**Comment by jrbudda** [comment]
scroll down and read the change notes.

**Comment by ylluminate** [comment]
Thanks, I guess it's a major flaw in Github insomuch that it doesn't update the release date shown to users:
![image](https://cl.ly/4c836450473b/Image%202019-01-20%20at%206.58.58%20PM.png)

Thanks for pointing it out. I've always watched for the date over the last 10 years on GH... O.o

**Comment by Espergium** [comment]
-Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true are missing from launch options.

**Comment by ylluminarious** [comment]
@Espergium Thanks, yup, that fixed it.
