### ISSUE TITLE
[QoL Request] Vivecraft installer checking local library

### ISSUE THREAD

**Issue by Espergium** [jrbudda/Vivecraft_112#87]
The vivecraft installer currently does not check the local machine for pre-existing compatible libraries. Is it feasible to have the installer check a specific folder first before fetching online? 
(Even as a fallback for a potential server/network outage?)

**Comment by Techjar** [comment]
You can already manually install OptiFine, simply place it in `.minecraft/libraries/optifine/OptiFine/<version>/`.
