### ISSUE TITLE
1.12.1 ?

### ISSUE THREAD

**Issue by xlar54** [jrbudda/Vivecraft_112#9]
Seems to only work with 1.12.  Can you update it for 1.12.1?

**Comment by jrbudda** [comment]
How long has 1.12.1 been out?

**Comment by xlar54** [comment]
Since 8/3.  Wasnt sure what the .1 change would mean for you.  Thank you for your efforts here.

**Comment by jrbudda** [comment]
I need Forge and Optifine to update, then rebuild against that version. Optifine's website is down so I'm not sure if he's updated yet.

**Comment by xlar54** [comment]
Oh ok.  Ill check back later.  Thank you.

**Comment by xlar54** [comment]
btw, i was able to use 1.12 optifine with 1.21.  I had to copy 1.12.1.json to the 1.12 directory and name it as such.  Vivecraft loads and runs, it just wont connect to a 1.12.1 server.

**Comment by jrbudda** [comment]
this needs testing https://github.com/jrbudda/Vivecraft_112/releases/tag/1.12.1-jrbudda-3

**Comment by xlar54** [comment]
nice thanks!
