### ISSUE TITLE
[1.12.2 Modded] Charset Mod Barrels Flickering/Invisible

### ISSUE THREAD

**Issue by nephatrine** [jrbudda/Vivecraft_112#90]
Barrels from [Charset Storage - Barrels](https://minecraft.curseforge.com/projects/charset-storage-barrels?gameCategorySlug=mc-mods&projectID=284529) render oddly. Sometimes the wood textures on them flicker wildly and other times they turn invisible. In both cases the item display on the front still displays and works so they're still "usable", but it's very distracting. **This does NOT happen with OptiFine alone - only in combination with ViveCraft VR mode.**

**Comment by Espergium** [comment]
Could you specify what version of vivecraft you're using, and if possible the version of the mod?

**Comment by nephatrine** [comment]
Sorry! Yes **Charset Storage Barrels 0.5.4.8** and **Vivecraft 1.12.2-jrbudda-7-r10**. Does not occur with non-vr vivecraft.

Forge is 1.12.2-14.23.5.2772 and VivecraftForgeExtensions-1.12.2-0.2.4.12.

**Comment by jrbudda** [comment]
I've been looking at this for like 2 days now. For me, the VR client renders all barrels as basic wood blocks, and the texture layer representing the bands and outline is missing. Works fine in the non-vr version but I can't find any reason for it. I have not seen any flickering tho. I'd like to fix this but at the moment I have no idea what's causing it.

**Comment by jrbudda** [comment]
OK this should be fixed in 7r12 now
